import assert from 'node:assert/strict';
import * as model from '../../dashboard/src/content/dashboard/shop-intake-model.js';
import * as m from '../../dashboard/src/content/dashboard/profit-model.js';
const checks=[];
function check(name,fn){fn();checks.push({name,passed:true});}
const target={target_id:'target-b',shop_id:'shop-b',status:'observed',tracking_status:'unconfigured',tracking_revision:0,can_configure_tracking:true,tracking_connection_status:'connection_pending'};
const receipt=(overrides={})=>({operation:'tracking',setting_status:'saved',target_id:target.target_id,shop_id:target.shop_id,tracking_status:'enabled',tracking_revision:1,dashboard_built:true,website_collection_performed:false,baseline_changed:false,history_deleted:false,tracking_connection_status:'connection_pending',...overrides});
check('unconfigured_paused_enabled_and_unloaded_are_distinct',()=>{assert.equal(model.targetTracking({...target,tracking_status:undefined}).status,'unavailable');for(const status of ['unconfigured','enabled','paused'])assert.equal(model.targetTracking({...target,tracking_status:status}).status,status);assert.equal(model.targetTracking({...target,tracking_revision:true}).loaded,false);});
check('tracking_payload_is_only_target_status_and_exact_revision',()=>{assert.deepEqual(model.trackingPayload(target,'enabled'),{target_id:target.target_id,status:'enabled',expected_revision:0});for(const changed of [{can_configure_tracking:false},{identity_conflict:true},{shop_id:null},{status:'needs_identity'},{tracking_revision:-1},{tracking_revision:NaN}])assert.throws(()=>model.trackingPayload({...target,...changed},'enabled'));assert.throws(()=>model.trackingPayload(target,'unconfigured'));});
check('strict_completion_rejects_wrong_shop_partial_or_collection_receipts',()=>{assert.equal(model.trackingCompletion({status:'succeeded',receipt:receipt()},target,'enabled').tracking_revision,1);for(const changed of [{shop_id:'shop-a'},{target_id:'target-a'},{dashboard_built:false},{website_collection_performed:true},{baseline_changed:true},{history_deleted:true},{tracking_revision:NaN},{tracking_status:'paused'},{operation:'register'}])assert.throws(()=>model.trackingCompletion({status:'succeeded',receipt:receipt(changed)},target,'enabled'));assert.throws(()=>model.trackingCompletion({status:'running',receipt:receipt()},target,'enabled'));});
const filters={priority:'all',search:''};
function row(id,value,extra={}){return {observation_id:id,opportunity_id:`o:${id}`,shop_id:'s',run_id:'r',view_order:id,title:'合成卡',priority_key:'eligible_reference',priority_order:3,sales_label:'已拼',sales_unit:'件',sales_precision:'exact_display',sales_value:value,...extra};}
check('same_sales_tie_original_position',()=>assert.deepEqual(m.filterOpportunities([row(3,50),row(1,11),row(2,50)],'s',filters).map(r=>r.observation_id),[2,3,1]));
check('yipin_yiqiang_rank_together_while_unit_fuzzy_null_bool_and_zero_stay_separate',()=>{const input=[row(1,999,{sales_label:'已抢'}),row(2,999,{sales_unit:'单'}),row(3,999,{sales_precision:'non_exact_or_unparsed'}),row(4,null),row(5,true),row(6,0),row(7,10),row(8,20),row(9,50)];assert.deepEqual(m.filterOpportunities(input,'s',filters).map(r=>r.observation_id),[1,9,8,2,3,4,5,6,7]);});
check('other_priority_tiers_keep_existing_rule_order',()=>{const input=[row(1,999),row(2,1,{priority_key:'new_candidate',priority_order:1}),row(3,2,{priority_key:'comparable_growth',priority_order:2}),row(4,500,{priority_key:'watch',priority_order:4})];assert.deepEqual(m.filterOpportunities(input,'s',filters).map(r=>r.observation_id),[2,3,1,4]);});
check('watch_not_reordered_by_incomparable_numeric_values',()=>{const input=[row(2,999,{priority_key:'watch',priority_order:4}),row(1,null,{priority_key:'watch',priority_order:4})];assert.deepEqual(m.filterOpportunities(input,'s',filters).map(r=>r.observation_id),[1,2]);});
check('old_schema_omits_first_seen_evidence_without_inventing_zero',()=>{assert.equal(m.arrivalEvidenceNote({new_candidate_count:3}),null);assert.equal(m.arrivalEvidenceNote(null),null);});
check('unknown_invalid_and_actual_zero_evidence_counts',()=>{for(const count of [null,-1,NaN,'531',true])assert.equal(m.arrivalEvidenceNote({arrival_evidence_count:count}),null);assert.equal(m.arrivalEvidenceNote({arrival_evidence_count:0,coverage_expansion_evidence_count:0}),'首见线索 0（其中可能补采旧存量 0） · 不等于新品，不与四档相加');assert.equal(m.arrivalEvidenceNote({arrival_evidence_count:1}),'首见线索 1 · 不等于新品，不与四档相加');});
export const acceptance={suite:'tracking_priority',passed:checks.length,total:checks.length,checks};
