import React,{useMemo,useState} from 'react';
import {DataComponent,Dropdown,Section,SectionHeader,SourceSidebar,useDataApp} from '../../data-app-public.jsx';
import {beijing,safeLink} from './pdd-model.js';
import {ARTIST_FILTERS,ARTIST_KIND_LABELS,ARTIST_SOURCE_LABELS,filterArtists,artistSourceScope,artistDrilldown,artistEvidenceFilters,artistReviewedSource,evidenceText} from './artist-research-model.js';
import './artist-research.css';

function ExternalLink({source,children}){
 const href=safeLink(source?.url);
 return href?<a href={href} target="_blank" rel="noopener noreferrer">{children||source.label||'公开入口'} ↗</a>:<span>{children||source?.label||'入口地址待核验'}</span>;
}
function SourceDetail({source}){
 return <div className="artist-source-detail"><strong><ExternalLink source={source}/></strong><dl><dt>核验状态</dt><dd>{evidenceText(source.verification)}</dd><dt>名称 / 认证依据</dt><dd><pre>{evidenceText(source.basis)}</pre></dd><dt>检查日期</dt><dd>{source.date_checked||'未记录'}</dd><dt>用途</dt><dd>{source.purpose||'仅查阅公开工作动态，具体活动与授权另行核实'}</dd></dl></div>;
}

export function ArtistResearchContent({shopId,onDrilldown}){
 const {queries}=useDataApp(),[filters,setFilters]=useState({...ARTIST_FILTERS}),[sourceRequest,setSourceRequest]=useState(null);
 const watchlist=queries.artist_watchlist?.rows||[],summaryRows=(queries.artist_research_summary?.rows||[]).filter(row=>row.shop_id===shopId),summary=summaryRows[0];
 const shops=queries.competitor_shops?.rows||[],shop=shops.find(row=>row.shop_id===shopId),run=(queries.runs?.rows||[]).find(row=>row.shop_id===shopId&&row.run_id===summary?.run_id);
 const rows=useMemo(()=>filterArtists(watchlist,shopId,filters),[watchlist,shopId,filters]);
 const scope=useMemo(()=>artistSourceScope(queries,shopId,rows),[queries,shopId,rows]);
 const channels=queries.artist_source_channels?.rows||[];
 const referenceScope=artistEvidenceFilters('reference',shopId,rows,summaryRows),watchScope=artistEvidenceFilters('watchlist',shopId,rows,summaryRows,filters),publicScope=artistEvidenceFilters('channels',shopId,rows,summaryRows);
 const openSource=(type,component)=>{if(type==='source')setSourceRequest(component);};
 const setFilter=(field,value)=>setFilters(previous=>({...previous,[field]:value}));
 const controls=<div className="artist-controls"><label className="artist-search">姓名或活动标题词<input type="search" value={filters.search} onChange={event=>setFilter('search',event.target.value)} placeholder="如：王安宇、演唱会、时装周"/></label><Dropdown label="人物类型" showLabel value={filters.kind} choices={['artist','esports','unresolved','all']} choiceLabels={ARTIST_KIND_LABELS} allLabel="全部类型" onChange={value=>setFilter('kind',value)}/><Dropdown label="公开来源" showLabel value={filters.source} choices={['all','verified','pending']} choiceLabels={ARTIST_SOURCE_LABELS} allLabel="全部入口状态" onChange={value=>setFilter('source',value)}/></div>;
 if(!queries.artist_watchlist)return <article className="artist-research"><SectionHeader id="artist-research-heading" title="明星与活动"/><p className="artist-empty">艺人标题线索与公开来源尚未载入。</p></article>;
 return <article className="artist-research"><SectionHeader id="artist-research-heading" title="明星与活动"/>
  <p className="artist-intro">从原卡标题定位艺人与活动词，再查公开发布。标题提及、活动日期与图片来源均待核对；账号入口核查不等于当前活动已核实或素材已获授权。</p>
  {summary&&<DataComponent id="artist-research-coverage" queryId="artist_research_summary" kind="metric" title="当前店铺的艺人线索覆盖" variant="plain" sourceRows={summaryRows} displayRows={summaryRows} scopeFilters={referenceScope} onOpen={openSource} description="当前店铺参考/最新两轮的检索名称，以及参考轮的标题覆盖；独立于下方姓名和入口筛选。多人标题可涉及多位艺人，艺人卡数不可相加为商品数。"><div className="artist-coverage" data-reviewed-rows="true"><div><strong>{shop?.shop_name||shopId}</strong><span>{run?.status==='complete'&&run?.end_boundary_observed?'历史完整参考':'部分参考'} · {run?beijing(run.observed_to):'观察时间待补'}</span></div><p><b>{summary.artist_count}</b> 个参考 / 最新轮检索名称{summary.reference_artist_count!==undefined&&<>（参考轮 {summary.reference_artist_count} 个）</>} · <b>{summary.verified_source_artist_count}</b> 位有核实入口</p><p>参考轮：<b>{summary.artist_card_count}</b> 张艺人相关原卡 / {summary.reference_card_count} 张参考卡 · 其中单卡销量 &gt;10：<b>{summary.artist_eligible_card_count}</b> 张</p><small>以上为当前店铺覆盖统计。多人卡可重复提及；入口依据可能仅搜索索引可见。</small></div></DataComponent>}
  {summary&&<details className="artist-methods"><summary>从标题线索到核验动作</summary><DataComponent id="artist-research-hypotheses" queryId="artist_research_summary" kind="table" title="事实、推断候选与核验动作" variant="plain" sourceRows={summaryRows} displayRows={summaryRows} scopeFilters={referenceScope} onOpen={openSource} description="全店参考轮研究建议，独立于上方名称筛选；推断候选不作为已发生事件或卖家真实意图。"><div className="artist-hypotheses" data-reviewed-rows="true">{(summary.hypotheses||[]).map((hypothesis,index)=><section key={index}><h3>{hypothesis.title}</h3><p><b>事实：</b>{hypothesis.fact}</p><p><b>推断候选：</b>{hypothesis.inference}</p><p><b>核验动作：</b>{hypothesis.action}</p></section>)}<p className="artist-muted">{summary.coverage_note}</p></div></DataComponent></details>}
  {queries.artist_source_channels&&<details className="artist-methods"><summary>通用公开信息渠道 · 跨店参考</summary><DataComponent id="artist-research-channels" scopeFilters={publicScope} onOpen={openSource} queryId="artist_source_channels" kind="table" title="通用公开来源入口" variant="plain" sourceRows={channels} displayRows={channels} description="公共渠道入口不属于任一店铺的采集结果，也不是艺人个人账号或当前活动清单。点击后由用户自行查阅，不自动采集。"><div className="artist-channels" data-reviewed-rows="true">{channels.map(channel=><SourceDetail key={channel.channel_id} source={channel}/>)}</div></DataComponent></details>}
  <Section id="artist-watchlist-heading" title="逐人查公开入口" spacing="content" filters={controls}>
   <DataComponent id="artist-watchlist" queryId="artist_watchlist" queryIds={['artist_watchlist','observations','runs']} kind="table" title="艺人查询与原卡下钻" variant="plain" sourceRows={rows} displayRows={rows} sourceRowsByQuery={{artist_watchlist:rows,observations:scope.observations,runs:scope.runs}} scopeFilters={watchScope} onOpen={openSource} description="当前店铺及人物/入口/搜索范围。按参考轮精确销量、件、单卡 >10 的卡数降序，仅用于核验顺序，不合计销量、不保证推荐。来源中参考轮和最新轮保留独立原卡，所有原卡下钻不追加销量门槛。">
    <div className="artist-results-note" data-reviewed-rows="true"><strong>{rows.length} 个名称 / 称呼</strong><span>按参考轮销量 &gt;10 卡数排列，仅核验优先级；不是艺人销量或推荐保证。</span></div>
    {rows.length?<div className="artist-table-wrap"><table className="artist-table" data-reviewed-rows="true"><thead><tr><th>艺人 / 标题称呼</th><th>参考轮原卡</th><th>标题中的活动词</th><th>公开入口与核验依据</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.shop_id}:${row.artist_id}`}>
     <td><strong className="artist-name">{row.artist_name}</strong><span className="artist-type">{ARTIST_KIND_LABELS[row.entity_kind]||'类型待核验'}</span>{row.identity_note&&<small>{row.identity_note}</small>}</td>
     <td><div className="artist-counts"><span><b>{row.reference_card_count}</b> 张提及卡</span><span>单卡销量 &gt;10：<b>{row.eligible_card_count}</b></span></div><button className="artist-link-button" disabled={!row.observation_ids?.length} onClick={()=>onDrilldown(artistDrilldown(row))}>查看全部原卡 ↗</button>{row.latest_run_id&&row.latest_run_id!==row.run_id&&<div className="artist-latest"><span>最新{row.latest_is_partial?'部分样本':'记录'}：{row.latest_card_count} 张提及卡</span><button className="artist-link-button" disabled={!row.latest_observation_ids?.length} onClick={()=>onDrilldown(artistDrilldown(row,'latest'))}>查看该轮 ↗</button></div>}</td>
     <td><small>参考轮</small>{row.title_event_clues?.length?<div className="artist-clues">{row.title_event_clues.map((clue,index)=><span key={`${clue.label}:${index}`}>{clue.label} <b>{clue.count} 卡</b></span>)}</div>:<span className="artist-muted">{row.reference_card_count?'标题未命中活动词':'无参考轮原卡'}</span>}{row.latest_run_id&&row.latest_run_id!==row.run_id&&<div className="artist-latest"><span>最新{row.latest_is_partial?'部分样本':'记录'} · 独立计数</span>{row.latest_title_event_clues?.length?<div className="artist-clues">{row.latest_title_event_clues.map((clue,index)=><span key={`${clue.label}:${index}`}>{clue.label} <b>{clue.count} 卡</b></span>)}</div>:<span>{row.latest_card_count?'标题未命中活动词':'本轮无提及原卡'}</span>}</div>}<small>标题线索，非已核实活动；词组可重叠，参考与最新轮不相加。</small><details className="artist-details"><summary>参考轮标题示例（最多5条）</summary>{row.reference_card_count?<><ul>{(row.title_examples||[]).slice(0,5).map(card=><li key={card.observation_id}>{card.title}<small>原卡 #{card.observation_id}</small></li>)}</ul><small>全部原标题可通过原卡下钻查看；搜索涵盖参考与最新轮全部标题。</small></>:<p>无参考轮原卡；请用“查看该轮”查阅最新观察原卡。</p>}</details></td>
     <td><span className="artist-source-status">{row.source_status||'入口待核验'}</span><div className="artist-source-links">{(row.sources||[]).map((source,index)=><ExternalLink key={`${source.url}:${index}`} source={source}/>)}</div>{!row.sources?.length&&<small>尚无核实入口，不按姓名猜账号。</small>}<details className="artist-details"><summary>逐条来源、检查日期与检索</summary>{(row.sources||[]).map((source,index)=><SourceDetail source={source} key={`${source.url}:${index}`}/>)}{row.search_links?.length>0&&<div className="artist-search-links"><strong>人工检索入口 · 待核验</strong>{row.search_links.map((source,index)=><div key={`${source.url}:${index}`}><ExternalLink source={source}/><small>{source.purpose||'检索结果不等于已核实官方账号'}</small></div>)}</div>}<small>线索整理：{row.research_checked_at||'未记录'}</small></details></td>
    </tr>)}</tbody></table></div>:<div className="artist-empty"><strong>当前筛选没有匹配项</strong><p>可清空搜索，或切换人物类型和入口状态。</p><button className="artist-link-button" onClick={()=>setFilters({...ARTIST_FILTERS})}>恢复娱乐艺人默认范围</button></div>}
   </DataComponent>
  </Section>
  {sourceRequest&&<SourceSidebar key={sourceRequest.id} component={sourceRequest} queries={queries} getSource={queryId=>artistReviewedSource(queries,sourceRequest,queryId)} onClose={()=>setSourceRequest(null)}/>}
 </article>;
}
