import React,{useEffect,useMemo,useRef,useState} from 'react';
import {DataComponent,Dialog,Dropdown,SectionHeader,SourceSidebar,useDataApp} from '../../data-app-public.jsx';
import {beijing,safeLink} from './pdd-model.js';
import {HEAT_FILTERS,emptyHeatPreferences,loadHeatPreferences,saveHeatPreferences,toggleHeatFollow,updateHeatPersonNote,upsertManualHeatPerson,removeManualHeatPerson,heatPreferenceBackup,filterHeatPeople,heatScopeFilters,heatEvidenceScope,reviewedHeatSource,readHeatStatus,startHeatRefresh,workChangeLabel,heatValueLabel,heatTimeNote,heatRefreshCompletion,heatReloadUrl} from './heat-watch-model.js';
import './heat-watch.css';

const PUBLIC_SCOPE=[{field:'scope',label:'来源范围',value:'独立公开作品榜；不继承店铺、拼多多轮次或个人关注筛选'}];
function Link({url,children}){const href=safeLink(url);return href?<a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>:<span>{children}</span>;}
function Work({work}){return <div className="heat-work"><div className="heat-work-heading"><strong>作品排名 {work.rank??'未知'}</strong><Link url={work.work_url}>《{work.title}》</Link></div><div className="heat-work-value"><span>{work.metric_label||'作品榜单值'} <b>{heatValueLabel(work)}</b></span><span>{workChangeLabel(work)}</span></div>{work.value_raw&&work.value_precision!=='exact_display'&&<small>保留展示原文，未作为精确值比较。</small>}<small>榜单更新原文：{work.source_updated_raw||(work.source_timestamp?beijing(work.source_timestamp):'来源未给出完整时间')} · 采集：{beijing(work.captured_at)}</small>{heatTimeNote(work)&&<small>{heatTimeNote(work)}</small>}<details><summary>作品比较依据</summary><pre>{JSON.stringify({work_url:work.work_url,metric_label:work.metric_label,value_raw:work.value_raw,value_precision:work.value_precision,source_timestamp:work.source_timestamp,source_updated_raw:work.source_updated_raw,time_status:work.time_status,timezone_assumption:work.timezone_assumption,captured_at:work.captured_at,previous_value:work.previous_value,delta:work.delta,previous_snapshot_id:work.previous_snapshot_id,change_status:work.change_status,comparison_reason:work.comparison_reason},null,2)}</pre></details></div>;}

export function HeatWatchContent(){
 const {queries,snapshot}=useDataApp(),awaitingRefresh=useRef(false);
 const [filters,setFilters]=useState({...HEAT_FILTERS}),[preferences,setPreferences]=useState(emptyHeatPreferences),[storageError,setStorageError]=useState(''),[storageReady,setStorageReady]=useState(false),[storageMessage,setStorageMessage]=useState('');
 const [job,setJob]=useState({status:'idle',message:''}),[starting,setStarting]=useState(false),[sourceRequest,setSourceRequest]=useState(null),[manualEditor,setManualEditor]=useState(null),[noteEditor,setNoteEditor]=useState(null),[backup,setBackup]=useState(null);
 const people=queries.artist_heat_people?.rows||[],summaryRows=queries.artist_heat_summary?.rows||[],summary=summaryRows[0],sources=queries.artist_heat_sources?.rows||[];
 const rows=useMemo(()=>filterHeatPeople(people,filters,preferences),[people,filters,preferences]),evidence=useMemo(()=>heatEvidenceScope(queries,rows),[queries,rows]),followed=new Set(preferences.follows);
 const openSource=(type,component)=>{if(type==='source')setSourceRequest(component);};
 function reloadPreferences(){try{const result=loadHeatPreferences(window.localStorage,snapshot.id);setPreferences(result.preferences);setStorageError(result.error);setStorageReady(!result.error);}catch(error){setStorageError(`读取本机关注失败：${error.message}。未覆盖已有记录。`);setStorageReady(false);}}
 function persist(next){if(!storageReady){setStorageError('关注记录尚未成功读取，暂不覆盖本机存储。请先重读关注。');return false;}try{const saved=saveHeatPreferences(window.localStorage,snapshot.id,next);setPreferences(saved);setStorageError('');setStorageMessage('已保存到此浏览器本机；未修改公开榜单。');return true;}catch(error){setStorageError(`保存失败：${error.message||'浏览器未允许存储'}。本次修改未保存，保留原关注。`);return false;}}
 useEffect(()=>{reloadPreferences();},[snapshot.id]);
 useEffect(()=>{const controller=new AbortController(),fetcher=(url,options)=>fetch(url,{...options,signal:controller.signal});readHeatStatus(fetcher).then(state=>{if(!controller.signal.aborted&&!awaitingRefresh.current)setJob(state);}).catch(error=>{if(!controller.signal.aborted&&!awaitingRefresh.current)setJob({status:'failed',message:error.message||'无法读取执行状态。'});});return()=>controller.abort();},[]);
 function receiveJob(state){const completion=heatRefreshCompletion(state,awaitingRefresh.current);if(completion.action==='reload'){awaitingRefresh.current=false;setJob({...state,message:'公开榜单与面板构建完成，正在重新载入新星观察…'});window.history.replaceState(window.history.state,'',heatReloadUrl(window.location.href));window.location.reload();}else if(completion.action==='error'){awaitingRefresh.current=false;setJob({status:'failed',message:completion.message});}else setJob(state);}
 useEffect(()=>{if(job.status!=='running')return;const controller=new AbortController(),fetcher=(url,options)=>fetch(url,{...options,signal:controller.signal});let timer;
  const poll=async()=>{try{const state=await readHeatStatus(fetcher);if(controller.signal.aborted)return;receiveJob(state);if(state.status==='running')timer=setTimeout(poll,1800);}catch(error){if(!controller.signal.aborted){awaitingRefresh.current=false;setJob({status:'failed',message:`执行状态读取失败：${error.message}；未确认更新成功。`});}}};
  timer=setTimeout(poll,1000);return()=>{controller.abort();clearTimeout(timer);};
 },[job.status]);
 async function refresh(){awaitingRefresh.current=true;setStarting(true);setJob({status:'idle',message:'正在请求更新公开作品榜并构建新快照…'});try{receiveJob(await startHeatRefresh(fetch));}catch(error){awaitingRefresh.current=false;setJob({status:'failed',message:error.message||'后台未连接，未更新成功。'});}finally{setStarting(false);}}
 function addManual(){setManualEditor({id:`manual:${crypto.randomUUID()}`,name:'',note:''});}
 function saveManual(){try{if(persist(upsertManualHeatPerson(preferences,manualEditor,new Date().toISOString())))setManualEditor(null);}catch(error){setStorageError(error.message);}}
 const filteredManual=preferences.manual.filter(row=>!filters.search.trim()||`${row.name} ${row.note}`.toLocaleLowerCase().includes(filters.search.trim().toLocaleLowerCase()));
 const absentFollowed=Object.entries(preferences.people).filter(([id])=>followed.has(id)&&!people.some(row=>row.person_id===id));
 const sourceViews={'heat-watch-coverage':{sourceRows:summaryRows,scopeFilters:PUBLIC_SCOPE},'heat-watch-people':{sourceRows:rows,sourceRowsByQuery:{artist_heat_people:rows,artist_heat_history:evidence.history,artist_heat_sources:evidence.sources},scopeFilters:heatScopeFilters(filters)},'heat-watch-sources':{sourceRows:sources,scopeFilters:PUBLIC_SCOPE}};
 const activeSource=sourceRequest?{...sourceRequest,...sourceViews[sourceRequest.id]}:null;
 return <article className="heat-watch"><SectionHeader id="heat-watch-heading" title="新星观察" filters={<button className="heat-primary" disabled={starting||job.status==='running'} onClick={refresh}>{starting||job.status==='running'?'正在更新…':'更新公开榜单'}</button>}/>
  <p className="heat-intro">先从公开作品认识名字。这里显示作品排名与热度，不是艺人指数；“本轮新认识”指原艺人目录之外的名字，不代表新出道或首次上榜。</p>
  <p className="heat-update-note">按钮只更新这一公开作品榜，不是全网明星榜。构建成功后会重新载入并留在本页；本机关注和备注保留，不会关注平台账号。</p>
  {job.message&&<p className={`heat-message ${job.status==='failed'?'is-error':''}`} role="status">{job.message}</p>}
  {queries.artist_heat_summary&&<DataComponent id="heat-watch-coverage" queryId="artist_heat_summary" kind="metric" title="公开榜单记录范围" variant="plain" sourceRows={summaryRows} displayRows={summaryRows} scopeFilters={PUBLIC_SCOPE} onOpen={openSource} description="本地保存的公开作品榜快照，独立于竞品店铺。页面可读的首批条目不代表完整榜；作品热度不等于演员个人热度。"><div className="heat-coverage" data-reviewed-rows="true">{summary?.status==='ready'?<><strong>{summary.work_count} 部作品 · {summary.person_count} 个平台显示名 · {summary.new_to_directory_count} 个目录外名字</strong><span>榜单更新原文：{summary.latest_source_updated_raw||(summary.latest_source_timestamp?beijing(summary.latest_source_timestamp):'未给出完整时间')}</span><span>采集：{beijing(summary.latest_captured_at)} · 已保存 {summary.snapshot_count} 次记录</span>{heatTimeNote(summary)&&<small>{heatTimeNote(summary)}</small>}{summary.freshness_note&&<small>{summary.freshness_note}</small>}<small>覆盖页面可读首批，非完整榜。{summary.snapshot_count<2?'首次记录，暂无较上次变化。':`${summary.comparison_available_count} 部作品有同口径比较；其余保留不可比原因。`}</small></>:<><strong>尚无已保存的公开榜单记录</strong><span>点击“更新公开榜单”后，以后台实际结果为准。</span></>}</div></DataComponent>}
  <details className="heat-guide"><summary>第一次接触：剧粉、个人粉、团粉和超话</summary><p><b>剧粉</b>主要围绕作品和角色；<b>个人粉</b>关注艺人本人及其公开作品；<b>团粉</b>关注组合及成员活动；<b>超话</b>是话题社区。一个人可能属于多类，这些称呼不能推断年龄、性别或购买力。</p></details>
  <div className="heat-controls"><label>姓名或作品<input type="search" value={filters.search} onChange={event=>setFilters(current=>({...current,search:event.target.value}))} placeholder="搜索名字或剧名"/></label><Dropdown label="发现范围" showLabel value={filters.discovery} choices={['new','all']} choiceLabels={{new:'本轮新认识',all:'本轮全部名字'}} allLabel="本轮全部名字" onChange={value=>setFilters(current=>({...current,discovery:value}))}/><label className="heat-follow-filter"><input type="checkbox" checked={filters.followedOnly} onChange={event=>setFilters(current=>({...current,followedOnly:event.target.checked,...(event.target.checked?{discovery:'all'}:{})}))}/>只看本机关注</label><button className="heat-text" onClick={addManual} disabled={!storageReady}>＋ 手工添加人物</button></div>
  {storageError&&<div className="heat-message is-error" role="status">{storageError}<button className="heat-text" onClick={reloadPreferences}>重读本机关注</button></div>}{storageMessage&&!storageError&&<small className="heat-storage-note" role="status">{storageMessage}</small>}
  {queries.artist_heat_people?<DataComponent id="heat-watch-people" queryId="artist_heat_people" queryIds={['artist_heat_people','artist_heat_history','artist_heat_sources']} kind="table" title="从关联作品认识人物" variant="plain" sourceRows={rows} displayRows={rows} sourceRowsByQuery={{artist_heat_people:rows,artist_heat_history:evidence.history,artist_heat_sources:evidence.sources}} scopeFilters={heatScopeFilters(filters)} onOpen={openSource} description="显示名来自来源作品的演职员/参与者字段，并非全网唯一身份。每部作品保留自己的排名、榜单值与同口径变化，不把多部作品相加为艺人分数。来源保留当前人物关联作品的全部已存历史，每期独立；关注仅影响人物浏览范围。"><div className="heat-result-note" data-reviewed-rows="true">{rows.length} 个名字 · 人物顺序不表示热度排名</div><div className="heat-people" data-reviewed-rows="true">{rows.map(person=><section className="heat-person" key={person.person_id}><div className="heat-person-intro"><header><h3>{person.name}</h3><button className={`heat-follow ${followed.has(person.person_id)?'is-followed':''}`} disabled={!storageReady} onClick={()=>persist(toggleHeatFollow(preferences,person))}>{followed.has(person.person_id)?'已关注 · 取消':'关注'}</button></header><p>{person.person_intro||person.identity_brief}</p><small>{person.in_artist_directory?'原艺人标题目录中有同名线索；身份仍需核对':'原艺人目录之外 · 本轮认识'}</small>{safeLink(person.person_url)&&<Link url={person.person_url}>平台人物资料</Link>}{followed.has(person.person_id)&&<><p className="heat-person-note">我的备注：{preferences.people[person.person_id]?.note||'未填写'}</p><button className="heat-text" onClick={()=>setNoteEditor({id:person.person_id,name:person.name,note:preferences.people[person.person_id]?.note||''})}>编辑备注</button></>}<details><summary>人物名称与认识依据</summary><p>{person.where_from}</p><p>{person.profile_basis||'同字名称仅代表来源显示名，不自动合并为全网唯一身份。'}</p><small>本地首次记录：{beijing(person.first_observed_at)}</small></details></div><div className="heat-person-works">{(person.associated_works||[]).map(work=><Work key={work.work_url} work={work}/>)}</div></section>)}</div>{!rows.length&&<div className="heat-empty">当前范围没有匹配名字。可切换“本轮全部名字”、清空搜索或查看下方个人笔记；这不表示没有新人。</div>}</DataComponent>:<p className="heat-empty">公开榜单尚未载入。后台未连接时不会生成示例人物或热度。</p>}
  <details className="heat-personal"><summary>我的关注与手工笔记（{storageReady?preferences.follows.length:'未读出'} 条，本机个人数据）</summary><p>手工人物由你填写，未核验身份；与公开榜单分开保存，也不代表已出道、已有作品或具备热度。</p><button className="heat-text" disabled={!storageReady} onClick={()=>setBackup({text:heatPreferenceBackup(preferences,snapshot.id,new Date().toISOString()),message:''})}>导出关注备份 JSON</button>{filteredManual.map(row=><div className="heat-manual-row" key={row.id}><div><strong>{row.name}</strong><span>用户自填 · 未核验</span><p>{row.note||'未填写备注'}</p></div><button className="heat-text" onClick={()=>setManualEditor({...row})}>编辑</button><button className="heat-text" disabled={!storageReady} onClick={()=>persist(removeManualHeatPerson(preferences,row.id))}>移除</button></div>)}{absentFollowed.map(([id,row])=><div className="heat-manual-row" key={id}><div><strong>{row.name}</strong><small>已关注来源名称，本轮作品榜未列出；不据此判断降温。</small><p>{row.note||'未填写备注'}</p></div><button className="heat-text" onClick={()=>setNoteEditor({id,name:row.name,note:row.note})}>备注</button><button className="heat-text" disabled={!storageReady} onClick={()=>persist(toggleHeatFollow(preferences,{person_id:id,name:row.name}))}>取消关注</button></div>)}{!filteredManual.length&&!absentFollowed.length&&<p className="heat-muted">尚无匹配的手工笔记或本轮未列出的关注。已上榜的关注在人物列表中查看。</p>}</details>
  {queries.artist_heat_sources&&<details className="heat-guide"><summary>公开榜单来源与限制</summary><DataComponent id="heat-watch-sources" queryId="artist_heat_sources" kind="table" title="公开作品榜来源" variant="plain" sourceRows={sources} displayRows={sources} scopeFilters={PUBLIC_SCOPE} onOpen={openSource} description="公共来源入口及成功/失败记录；不继承店铺或拼多多轮次。"><div data-reviewed-rows="true">{sources.map((source,index)=><div className="heat-source" key={source.source_id||index}><Link url={source.url||source.source_url}>{source.label||source.source_name||source.source_id||'公开来源'}</Link><pre>{JSON.stringify(source,null,2)}</pre></div>)}</div></DataComponent></details>}
  <Dialog open={Boolean(manualEditor)} onClose={()=>setManualEditor(null)} title="手工人物笔记 · 未核验">{manualEditor&&<div className="heat-editor"><p>这里只保存个人检索线索，不会创建已核实人物或添加作品热度。</p><label>名称或称呼<input maxLength={120} value={manualEditor.name} onChange={event=>setManualEditor(current=>({...current,name:event.target.value}))}/></label><label>我的备注<textarea rows={4} maxLength={2000} value={manualEditor.note} onChange={event=>setManualEditor(current=>({...current,note:event.target.value}))}/></label>{storageError&&<p role="status">{storageError}</p>}<button className="heat-primary" disabled={!storageReady} onClick={saveManual}>保存到本机关注</button></div>}</Dialog>
  <Dialog open={Boolean(noteEditor)} onClose={()=>setNoteEditor(null)} title="我的人物备注">{noteEditor&&<div className="heat-editor"><strong>{noteEditor.name}</strong><textarea aria-label="个人备注" rows={4} maxLength={2000} value={noteEditor.note} onChange={event=>setNoteEditor(current=>({...current,note:event.target.value}))}/><button className="heat-primary" disabled={!storageReady} onClick={()=>{if(persist(updateHeatPersonNote(preferences,noteEditor.id,noteEditor.note)))setNoteEditor(null);}}>保存个人备注</button></div>}</Dialog>
  <Dialog open={Boolean(backup)} onClose={()=>setBackup(null)} title="本机关注备份">{backup&&<div className="heat-editor"><p>完整 JSON，可选择并复制保存。只含本机关注和个人笔记，不含公开热度数据。</p><textarea aria-label="完整关注备份 JSON" readOnly rows={12} value={backup.text} onFocus={event=>event.currentTarget.select()}/><button className="heat-primary" onClick={async()=>{try{await navigator.clipboard.writeText(backup.text);setBackup(current=>({...current,message:'完整关注备份已复制。'}));}catch{setBackup(current=>({...current,message:'浏览器未允许自动复制；可在上方选择完整文本并复制。'}));}}}>复制完整 JSON</button><p role="status">{backup.message}</p></div>}</Dialog>
  {activeSource&&<SourceSidebar key={activeSource.id} component={activeSource} queries={queries} getSource={queryId=>reviewedHeatSource(queries,activeSource,queryId)} onClose={()=>setSourceRequest(null)}/>}
 </article>;
}
