import React,{useEffect,useMemo,useState} from 'react';
import {DataComponent,Dropdown,Section,SectionHeader,SourceSidebar,useDataApp} from '../../data-app-public.jsx';
import {historyReviewedSource} from './history-source-model.js';
import {beijing,safeLink} from './pdd-model.js';
import {DIMENSION_LABELS,TARGET_STATUS,TARGET_IDENTITY,shopScope,makeDrilldown,conciseText,scopeShopData,dimensionLabel} from './portfolio-model.js';

function Window({from,to,complete,label}){return <div className="portfolio-window"><strong>{label|| (complete?'完整参考':'部分观察')}</strong><span>{beijing(from)}</span><span>至 {beijing(to)}</span>{!complete&&<small>仅覆盖已采范围</small>}</div>;}
function EvidenceList({rows,empty}){return rows?.length?<ul>{rows.map((row,index)=><li key={index}>{conciseText(row)}</li>)}</ul>:<p className="portfolio-muted">{empty}</p>;}
export function PortfolioContent({shopId,onSelectShop,onDrilldown,onAddShop,onSelectTarget}){
 const {queries,snapshot}=useDataApp(),shops=queries.competitor_shops?.rows||[],shop=shops.find(row=>row.shop_id===shopId),products=queries.competitor_products?.rows||[],targets=queries.competitor_targets?.rows||[];
 const [dimensionKey,setDimensionKey]=useState('sales_bucket'),[sourceRequest,setSourceRequest]=useState(null);
 const openSource=(type,component)=>{if(type==='source')setSourceRequest({shopId,component});},activeSource=sourceRequest?.shopId===shopId?sourceRequest.component:null;
 useEffect(()=>setSourceRequest(null),[shopId,dimensionKey]);
 const getSource=queryId=>{const result=historyReviewedSource(queries,activeSource,queryId);return result&&['portfolio-dimensions','portfolio-strategy'].includes(activeSource?.id)?{...result,filters:result.filters.map(filter=>filter.field==='run_id'?{...filter,label:`店铺范围：${shop?.shop_name||shopId} · ${filter.label}`} :filter)}:result;};
 const shopDimensions=useMemo(()=>(queries.competitor_dimensions?.rows||[]).filter(row=>row.shop_id===shopId),[queries.competitor_dimensions,shopId]);
 const keys=Object.keys(DIMENSION_LABELS).filter(key=>shopDimensions.some(row=>row.dimension_key===key)),activeKey=keys.includes(dimensionKey)?dimensionKey:keys[0];
 const dimensions=shopDimensions.filter(row=>row.dimension_key===activeKey),strategy=(queries.competitor_strategy?.rows||[]).filter(row=>row.shop_id===shopId);
 const dimensionIds=new Set(dimensions.flatMap(row=>row.observation_ids||[]).map(String)),dimensionProducts=products.filter(row=>row.shop_id===shopId&&dimensions.some(dim=>dim.run_id===row.run_id)&&dimensionIds.has(String(row.observation_id)));
 const strategyIds=new Set(strategy.flatMap(row=>[...(row.supporting_observation_ids||[]),...(row.observation_ids||[])]).map(String)),strategyComparisonIds=new Set(strategy.flatMap(row=>row.basis_comparison_item_ids||[]));
 const strategyObservations=scopeShopData(queries,shopId).observations.filter(row=>strategyIds.has(String(row.observation_id))),strategyComparisons=scopeShopData(queries,shopId).items.filter(row=>strategyComparisonIds.has(row.comparison_item_id));
 const scheduler=snapshot.metadata?.collection_scheduler||{};
 const scheduleState={pending:'连接待完成',unknown:'连接状态未知',not_connected:'尚未接通',disabled:'未启用',enabled:'触发器已启用，逐店执行仍需证据'}[scheduler.scheduler_state]||'状态待核实';
 return <article className="portfolio"><SectionHeader id="portfolio-overview-heading" title="竞品总览" filters={<button className="pdd-export" onClick={onAddShop}>＋ 新增待分析店铺</button>}/>
 <p className="portfolio-intro">每家店按自己的真实观察独立分析。先看销量结构、价位与标题线索，再下钻原卡核验；这些是前台展示证据，不能推断利润或卖家真实意图。</p>
 {queries.competitor_shops?<DataComponent onOpen={openSource} id="portfolio-shops" queryId="competitor_shops" kind="table" title="店铺范围与覆盖" variant="plain" sourceRows={shops} displayRows={shops} description="每店采用最近有结束边界的完整轮作为分析参考；没有完整轮才使用部分轮。较新的部分记录单独展示，不与历史参考合并，不跨店直接排名。"><div className="portfolio-comparison-note" data-reviewed-rows="true"><strong>{shops.length} 家有真实观察的店铺</strong><span>不同观察时间与覆盖范围不可直接排名；卡片数不等于唯一商品或 SKU 数。</span></div><div className="portfolio-table-wrap"><table className="portfolio-table portfolio-shops-table" data-reviewed-rows="true"><thead><tr><th>店铺</th><th>分析参考窗口</th><th>最新记录窗口</th><th>参考轮销量结构</th><th>参考轮资料覆盖</th><th>查阅</th></tr></thead><tbody>{shops.map(row=><tr key={row.shop_id} className={row.shop_id===shopId?'is-selected':''}><td><button className="portfolio-shop-button" onClick={()=>onSelectShop(row.shop_id)}>{row.shop_name||row.shop_id}</button><small>{row.historical_run_count} 轮独立历史</small></td><td><Window from={row.reference_observed_from} to={row.reference_observed_to} complete={row.reference_scope==='complete_storefront'}/></td><td><Window from={row.latest_observed_from} to={row.latest_observed_to} complete={row.latest_is_complete} label={row.latest_is_complete?'最新完整记录':'最新部分记录'}/></td><td><strong>{row.card_count} 张原卡</strong><small>销量 &gt;10：{row.eligible_card_count}</small><small>已有销量：{row.yipin_positive_card_count}</small><small>销量未显示：{row.missing_sales_card_count}</small></td><td><span>本地图 {row.image_cached_count} / {row.card_count}</span><small>唯一 ID {row.identity_unique_count} / {row.card_count}</small><small>原金额可解析 {row.price_parsed_count} / {row.card_count}</small></td><td><button className="pdd-text-button" onClick={()=>onDrilldown(makeDrilldown(row,'本店分析参考轮 · 全部原卡','competitor_shops'))}>全部原卡 ↗</button><details className="pdd-evidence"><summary>参考选择与来源</summary><p>{row.reference_selection==='latest_complete_with_boundary'?'最近有结束边界的完整轮':'无完整参考，使用最近部分轮'}</p><pre>{JSON.stringify(row,null,2)}</pre></details></td></tr>)}</tbody></table></div></DataComponent>:<div className="portfolio-empty">多店分析查询尚未载入；可先查阅已存商品池与历史。</div>}
 {shop&&<><div className="portfolio-selected-context" data-reviewed-rows="true"><strong>当前分析：{shop.shop_name||shop.shop_id}</strong><span>{shop.reference_scope==='complete_storefront'?'历史完整参考':'部分样本参考'} · {beijing(shop.reference_observed_to)} · {shop.card_count} 张原卡</span></div>
 <Section id="portfolio-dimensions-heading" title="从结构定位原卡" spacing="content" filters={keys.length?<Dropdown label="分析维度" showLabel value={activeKey} choices={keys} choiceLabels={DIMENSION_LABELS} onChange={setDimensionKey}/>:null}>{queries.competitor_dimensions&&<DataComponent onOpen={openSource} id="portfolio-dimensions" queryId="competitor_dimensions" queryIds={['competitor_dimensions','competitor_products']} kind="table" title={DIMENSION_LABELS[activeKey]||'维度结构'} variant="plain" sourceRows={dimensions} displayRows={dimensions} sourceRowsByQuery={{competitor_dimensions:dimensions,competitor_products:dimensionProducts}} scopeFilters={[...shopScope(shopId),{field:'dimension_key',label:'分析维度',value:activeKey||'无已记录维度'}]} description="计数对应当前店铺参考轮的独立原卡。点击查看该行全部卡片，包含低销量与未知销量，入口不追加61张主门槛；标题品类只是词命中线索，非平台分类。"><div className="portfolio-table-wrap"><table className="portfolio-table portfolio-dimension-table" data-reviewed-rows="true"><thead><tr><th>结构 / 线索</th><th>全部原卡</th><th>其中单卡销量 &gt;10</th><th>口径与下钻</th></tr></thead><tbody>{dimensions.map(row=><tr key={row.dimension_id}><td><strong>{dimensionLabel(row)}</strong>{row.qualifiers?.price_condition&&<small>展示金额条件独立，不能视为同规格到手价</small>}</td><td className="portfolio-number">{row.card_count}<span className="portfolio-share-track"><i style={{width:`${row.denominator_card_count?Math.min(100,row.card_count/row.denominator_card_count*100):0}%`}}/></span><small>/ {row.denominator_card_count} 张参考卡</small></td><td className="portfolio-number">{row.eligible_card_count}</td><td><button className="pdd-text-button" onClick={()=>onDrilldown(makeDrilldown(row,`${DIMENSION_LABELS[row.dimension_key]} · ${dimensionLabel(row)}`,'competitor_dimensions'))}>查看全部 {row.card_count} 张原卡 ↗</button><small>{row.definition}</small>{row.counts_overlap&&<small>分组可重叠，不相加</small>}<details className="pdd-evidence"><summary>条件与原卡范围</summary><pre>{JSON.stringify({dimension_id:row.dimension_id,run_id:row.run_id,qualifiers:row.qualifiers,observation_ids:row.observation_ids},null,2)}</pre></details></td></tr>)}</tbody></table></div>{!dimensions.length&&<p>当前店铺没有此维度的已导出结果。</p>}</DataComponent>}</Section>
 <Section id="portfolio-strategy-heading" title="基于证据的策略线索" spacing="content">{queries.competitor_strategy&&<DataComponent onOpen={openSource} id="portfolio-strategy" queryId="competitor_strategy" queryIds={['competitor_strategy','observations','comparison_items']} kind="table" title="事实、解释候选与核验动作" variant="plain" sourceRows={strategy} displayRows={strategy} sourceRowsByQuery={{competitor_strategy:strategy,observations:strategyObservations,comparison_items:strategyComparisons}} scopeFilters={shopScope(shopId)} description="规则输出分为已观察事实、尚未核实的解释候选和建议动作。阈值及源卡可查；不提供综合分数、不推断真实利润、销量意图或唯一SKU。"><div className="portfolio-strategies" data-reviewed-rows="true">{strategy.map(row=><section className="portfolio-strategy" key={row.strategy_id}><header><h3>{row.title}</h3><button className="pdd-text-button" disabled={!row.observation_ids?.length} onClick={()=>onDrilldown(makeDrilldown(row,row.title,'competitor_strategy'))}>关联原卡 ↗</button></header><div className="portfolio-strategy-grid"><div><span className="portfolio-column-label">已观察事实</span><EvidenceList rows={row.facts} empty="没有足够事实"/></div><div><span className="portfolio-column-label">解释候选 · 待核验</span><EvidenceList rows={row.interpretation_candidates} empty="不据此推断意图"/></div><div><span className="portfolio-column-label">建议动作</span><EvidenceList rows={row.followup_actions} empty="补齐原始证据后再判断"/></div></div><details className="pdd-evidence"><summary>规则阈值、范围与未知项</summary><EvidenceList rows={row.unknowns} empty="按所列规则保留局限"/><pre>{JSON.stringify({rule_id:row.rule_id,thresholds:row.thresholds,scope:row.scope,run_id:row.run_id,basis_comparison_item_ids:row.basis_comparison_item_ids},null,2)}</pre></details></section>)}</div>{!strategy.length&&<p>当前店铺尚无足够的已导出策略依据。</p>}</DataComponent>}</Section></>}
 <Section id="portfolio-targets-heading" title="分析目标与采集连接" spacing="content">{queries.competitor_targets&&<DataComponent onOpen={openSource} id="portfolio-targets" queryId="competitor_targets" kind="table" title="已观察与待处理目标" variant="plain" sourceRows={targets} displayRows={targets} description="登记只是本地目标配置，不代表已采集。仅名称和未解析分享链接需要身份核实；不会按名称自动并入同名店铺。"><div className="portfolio-targets" data-reviewed-rows="true">{targets.map(row=><div className="portfolio-target" key={row.target_id}><div><strong>{row.display_name||'待核实店铺'}</strong><small>{row.identity_conflict?'与已存身份线索冲突，待核实':TARGET_IDENTITY[row.identity_status]||'身份待核实'}</small></div><span className="portfolio-status">{TARGET_STATUS[row.status]||'状态待核实'}</span><span>{row.run_count} 轮观察</span><button type="button" className="pdd-text-button" onClick={()=>onSelectTarget?.(row.target_id)}>查看目标 ↗</button>{safeLink(row.source_url)&&<a href={safeLink(row.source_url)} target="_blank" rel="noopener noreferrer">原始链接 ↗</a>}</div>)}</div></DataComponent>}
 <DataComponent onOpen={openSource} id="portfolio-global-schedule" queryId="collection_schedule" kind="metric" title="全局采集连接边界" variant="plain" sourceRows={queries.collection_schedule?.rows||[]} displayRows={queries.collection_schedule?.rows||[]} description="全局计划与连接元信息独立于各店是否已采集；不将全局状态视为逐店接通或成功。"><p className="portfolio-global-plan" data-reviewed-rows="true"><strong>全局计划：08:00 / 20:00（北京时间） · {scheduleState}</strong><span>全局计划不代表每家店已接入或已采集；逐店结果以实际轮次与执行证据为准。</span></p></DataComponent></Section>{activeSource&&<SourceSidebar key={activeSource.id} component={activeSource} queries={queries} getSource={getSource} onClose={()=>setSourceRequest(null)}/>}</article>;
}
