import {verifiedCardImage} from './verified-image.js';
import {ZoomableImage} from './ZoomableImage.jsx';
import {SkuPanel} from './CollectionControls.jsx';
import React,{useEffect,useMemo,useState} from 'react';
import {DataComponent,Dropdown,Dialog,Section,SectionHeader,SortableItem,SortableRegion,SourceSidebar,useDataApp} from '../../data-app-public.jsx';
import {historyReviewedSource} from './history-source-model.js';
import {EMPTY_FILTERS,INITIAL_FILTERS,BAND_LABELS,ID_LABELS,IMAGE_LABELS,PRECISION_LABELS,labelUnitKey,imageState,bandMatches,SALES_SORT_DESCRIPTION,filterCards,relatedCandidates,chooseDefaultRun,beijing,safeLink,filterScope,eligible,parseDisplayPrice,strategyIssues,buildPeerEvidence,selectionEvidence,applyWatchBand,WATCH_LABELS,observationBand} from './pdd-model.js';
import './pdd-dashboard.css';
import {scopeShopData,shopScope,applyDrilldown} from './portfolio-model.js';

function LocalImage({row,images,large=false}){
 const src=verifiedCardImage(row,images);
 return src?<ZoomableImage className={large?'pdd-image-large':'pdd-thumb'} src={src} alt={row.title}/>:<div className={large?'pdd-placeholder pdd-placeholder-large':'pdd-placeholder'}><svg viewBox="0 0 32 32" aria-hidden="true"><rect x="5" y="6" width="22" height="20" rx="4"/><circle cx="12" cy="12" r="2"/><path d="m6 23 7-7 5 5 3-3 5 5"/></svg><span>{IMAGE_LABELS[imageState(row)]}</span></div>;
}
function Card({row,images,onSelect,comparison=false,matched=false,peerEvidence}){
 const peer=peerEvidence.get(row.observation_id),band=observationBand(row);
 return <article className={`pdd-product${comparison?' pdd-product-compare':''}${matched?' pdd-matched':''}`} data-reviewed-rows="true" data-observation-id={row.observation_id}>
 <LocalImage row={row} images={images}/>
 <div className="pdd-product-body"><div className="pdd-product-top"><span>原位置 #{row.view_order}</span>{eligible(row)&&<span className="pdd-chip pdd-chip-positive">销量 &gt;10</span>}{comparison&&matched&&<span className="pdd-chip">匹配筛选</span>}</div>
 <button className="pdd-product-title" onClick={()=>onSelect(row)}>{row.title}</button><div className="pdd-product-value"><strong className={row.sales_raw?'':'pdd-muted'}>{row.sales_raw||'销量未显示'}</strong><span>{row.price_raw||'价格未显示'}</span></div>
 <div className="pdd-card-reason"><span>{eligible(row)?`单卡达标 · ${band}`:comparison&&!matched?'未匹配的原始对照卡':'原始观察参考'}</span>{peer&&<span>同标题 {peer.eligible_count} 张各自 &gt;10 · 不相加</span>}</div>
 <div className="pdd-product-bottom"><span>{ID_LABELS[row.identity_status]||'身份待核验'}</span><button className="pdd-text-button" onClick={()=>onSelect(row)}>理由与待核验 ↗</button></div></div></article>;
}
function Detail({row,run,images,onClose,filters,peerEvidence,matched}){
 const goodsLink=safeLink(row?.goods_url),imageLink=safeLink(row?.image_url);
 const evidence=row?selectionEvidence(row,matched?filters:EMPTY_FILTERS,peerEvidence):null;
 return <Dialog open={Boolean(row)} onClose={onClose} title={row?`原位置 #${row.view_order} · 商品卡片`:'商品详情'} className="pdd-detail-dialog">{row&&<div className="pdd-detail" data-reviewed-rows="true"><LocalImage row={row} images={images} large/><h3>{row.title}</h3>
 <SkuPanel row={row}/><div className="pdd-detail-values"><strong>{row.sales_raw||'销量未显示'}</strong><span>{row.price_raw||'价格未显示'}</span></div><p className="pdd-detail-note">展示价尚未核实同规格、券、数量与运费条件；前台展示数不等于已核实订单。</p>
 <div className="pdd-detail-rules"><h4>{matched?'当前筛选的匹配依据':'原始对照事实（未匹配当前筛选）'}</h4><ul>{evidence.matched_reasons.map(text=><li key={text}>{text}</li>)}</ul><h4>跟款前待核验</h4><ul>{evidence.verification_gaps.map(text=><li key={text}>{text}</li>)}</ul></div>
 <dl><dt>商品身份</dt><dd>{ID_LABELS[row.identity_status]||'待核验'}{row.goods_id?` · ${row.goods_id}`:''}</dd><dt>主图状态</dt><dd>{IMAGE_LABELS[imageState(row)]}；失败不自动重试</dd><dt>观察时刻</dt><dd>{beijing(row.observed_at)}（北京时间）</dd><dt>时间精度</dt><dd>{PRECISION_LABELS[row.observed_at_precision]||'待核验'}</dd></dl>
 <div className="pdd-detail-links">{goodsLink?<a href={goodsLink} target="_blank" rel="noopener noreferrer">打开已记录商品链接 ↗</a>:<span className="pdd-muted">商品链接待补</span>}{imageLink&&<a href={imageLink} target="_blank" rel="noopener noreferrer">手动打开原图网址 ↗</a>}</div>
 <details className="pdd-evidence"><summary>原文与来源详情</summary><pre>{row.original?.cardText||row.original?.rawText||row.title}</pre><dl><dt>原始销量口径</dt><dd>{row.sales_label||'未知'} · {row.sales_value??'未知'} · {row.sales_unit||'单位未知'} · {row.sales_precision}</dd><dt>记录 ID</dt><dd>{row.observation_id}</dd><dt>轮次</dt><dd>{row.run_id}</dd><dt>来源 SHA-256</dt><dd>{run?.snapshot_sha256}</dd><dt>主图 SHA-256</dt><dd>{row.asset_sha256||'待补'}</dd><dt>末次页面读取</dt><dd>{beijing(row.last_dom_read_at)}</dd><dt>图片历史说明</dt><dd>{row.previous_attempt_reason||'无已记录失败说明'}</dd></dl></details></div>}</Dialog>;
}
function prepareFilteredExport(rows,run,filters,peerEvidence,drilldown){
 const payload={export_type:'pdd_filtered_card_reference',exported_at:new Date().toISOString(),shop_id:run.shop_id,dimension_scope:drilldown||null,run:{shop_id:run.shop_id,run_id:run.run_id,status:run.status,observed_from:run.observed_from,observed_to:run.observed_to,snapshot_sha256:run.snapshot_sha256},filters:{...filters},card_count:rows.length,limitations:['每张卡片独立；同标题不确认同 SKU，不合计销量，不跨轮累计。','展示价仅用于原金额筛选，不是采购成本或核实到手价；价格范围或多值保留原文且不猜测。','11–30 / 31–100 / >100 为可调的人工观察档；不代表盈利、爆款、新品或真实增长。'],rows:rows.map(row=>({...row,selection_evidence:selectionEvidence(row,filters,peerEvidence)}))};
 return {token:{},text:JSON.stringify(payload,null,2),cardCount:rows.length,runId:run.run_id,runLabel:`${run.status==='complete'&&run.end_boundary_observed?'完整参考':'部分采集'} · ${beijing(run.observed_to)}`,conditions:[...shopScope(run.shop_id),...(drilldown?[{field:'observation_id',label:'维度下钻范围',value:drilldown.label}]:[]),...filterScope(filters)],sortLabel:filters.sort==='sales'?SALES_SORT_DESCRIPTION:filters.sort==='evidence'?'本地图 → ID 可查 → 原位置（核验资料顺序）':'原列表顺序',message:'',copying:false};
}
function requestJsonDownload(text){
 const url=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'})),anchor=document.createElement('a');
 try{anchor.href=url;anchor.download='竞品筛选结果.json';anchor.click();}finally{setTimeout(()=>URL.revokeObjectURL(url),30000);}
}
function FilteredExportDialog({document:exportDocument,onClose,onCopy,onDownload}){
 return <Dialog open={Boolean(exportDocument)} onClose={onClose} title="导出筛选 JSON" expanded className="pdd-export-dialog">{exportDocument&&<div data-reviewed-rows="true">
 <p><strong>{exportDocument.cardCount} 张筛选卡片</strong> · 包含当前筛选的全部结果，不限当前页。</p>
 <dl><dt>观察轮次</dt><dd>{exportDocument.runLabel}</dd><dt>轮次 ID</dt><dd>{exportDocument.runId}</dd><dt>当前条件</dt><dd>{exportDocument.conditions.length?exportDocument.conditions.map(item=>`${item.label}：${item.value}`).join('；'):'全部卡片，未添加商品筛选'}</dd><dt>排序</dt><dd>{exportDocument.sortLabel}</dd></dl>
 <p className="pdd-detail-note">下方仅预览前 6000 字符；完整 JSON 共 {exportDocument.text.length.toLocaleString()} 字符。复制与下载使用全文，更换筛选、轮次或数据后需重新打开导出。</p>
 <label style={{display:'block'}}><strong>筛选 JSON 预览（最多 6000 字符，非完整文件）</strong><textarea aria-label="筛选 JSON 预览，最多 6000 字符" readOnly value={exportDocument.text.slice(0,6000)} spellCheck={false} style={{display:'block',width:'100%',minHeight:260,maxHeight:'45vh',boxSizing:'border-box',marginTop:8,fontFamily:'ui-monospace,monospace',fontSize:12,resize:'vertical'}}/></label>
 <div className="pdd-detail-links"><button className="pdd-export" disabled={exportDocument.copying} onClick={onCopy}>{exportDocument.copying?'正在复制…':'复制 JSON'}</button><button className="pdd-export" onClick={onDownload}>下载 JSON</button></div>
 <p role="status" aria-live="polite">{exportDocument.message||'可复制完整 JSON，或请求浏览器下载。'}</p>
 </div>}</Dialog>;
}
function StrategyControls({filters,setFilters,onRestore}){
 const setBound=(field,value)=>setFilters(current=>({...current,[field]:value,...(field.startsWith('sales')?{watchBand:'custom',labelUnit:'all',band:'all'}:{})}));
 return <div className="pdd-strategy-controls"><div className="pdd-strategy-title"><div><strong>试款核验队列</strong><span>默认单卡销量 &gt;10 件，不限展示价；先看资料再核验成本。</span></div><button className="pdd-reset" onClick={()=>{onRestore?.();setFilters({...INITIAL_FILTERS});}}>恢复默认队列</button></div>
 <div className="pdd-strategy-grid"><Dropdown label="人工观察档" allLabel={WATCH_LABELS.all} showLabel value={filters.watchBand} choices={Object.keys(WATCH_LABELS)} choiceLabels={WATCH_LABELS} onChange={value=>setFilters(current=>applyWatchBand(current,value))}/>
 <fieldset className="pdd-range"><legend>精确销量 · 件</legend><input aria-label="精确销量下限" type="number" min="0" step="1" inputMode="numeric" value={filters.salesMin} onChange={event=>setBound('salesMin',event.target.value)} placeholder="不限"/><span>至</span><input aria-label="精确销量上限" type="number" min="0" step="1" inputMode="numeric" value={filters.salesMax} onChange={event=>setBound('salesMax',event.target.value)} placeholder="不限"/></fieldset>
 <fieldset className="pdd-range"><legend>原展示金额 · ¥（非成本）</legend><input aria-label="展示金额下限" type="number" min="0" step="0.01" inputMode="decimal" value={filters.priceMin} onChange={event=>setBound('priceMin',event.target.value)} placeholder="不限"/><span>至</span><input aria-label="展示金额上限" type="number" min="0" step="0.01" inputMode="decimal" value={filters.priceMax} onChange={event=>setBound('priceMax',event.target.value)} placeholder="不限"/></fieldset>
 <label className="pdd-theme"><span>主题词 · 任一包含</span><input aria-label="主题词，空格分隔任一匹配" value={filters.theme} onChange={event=>setFilters(current=>({...current,theme:event.target.value}))} placeholder="如：立牌 挂件"/></label></div>
 <label className="pdd-peer-toggle"><input type="checkbox" checked={filters.peerConfirmed} onChange={event=>setFilters(current=>({...current,peerConfirmed:event.target.checked}))}/><span>同标题至少 2 张各自销量 &gt;10 件，只选单卡达标项</span></label><small>观察档是人工范围，可直接改数值；同标题不确认同 SKU，销量不相加。</small></div>;
}
export function ProductPool({shopId,drilldown}){
 const {queries,snapshot,filters:pageFilters,setFilter,visible}=useDataApp();
 const shopData=useMemo(()=>scopeShopData(queries,shopId),[queries.runs,queries.observations,shopId]),runs=shopData.runs,allRows=shopData.observations,defaultRun=chooseDefaultRun(runs);
 const [activeDrilldown,setActiveDrilldown]=useState(drilldown?.shop_id===shopId?drilldown:null);
 const selectedRunId=activeDrilldown&&runs.some(r=>r.run_id===activeDrilldown.run_id)?activeDrilldown.run_id:runs.some(r=>r.run_id===pageFilters.run_id)?pageFilters.run_id:defaultRun?.run_id,run=runs.find(r=>r.run_id===selectedRunId);
 const [filters,setFilters]=useState({... (drilldown?EMPTY_FILTERS:INITIAL_FILTERS)}),[page,setPage]=useState(0),[detail,setDetail]=useState(null),[exportDocument,setExportDocument]=useState(null),[sourceRequest,setSourceRequest]=useState(null);
 const openSource=(type,component)=>{if(type==='source')setSourceRequest({shopId,runId:selectedRunId,component});},activeSource=sourceRequest?.shopId===shopId&&sourceRequest?.runId===selectedRunId?sourceRequest.component:null;
 useEffect(()=>setSourceRequest(null),[shopId,selectedRunId,filters]);
 const images=useMemo(()=>new Map((queries.image_assets?.rows||[]).map(a=>[a.sha256,a])),[queries.image_assets]);
 const runRows=useMemo(()=>allRows.filter(r=>r.run_id===selectedRunId),[allRows,selectedRunId]);
 const runGroups=useMemo(()=>(queries.candidate_groups?.rows||[]).filter(g=>g.run_id===selectedRunId),[queries.candidate_groups,selectedRunId]);
 const peerEvidence=useMemo(()=>buildPeerEvidence(runGroups,runRows),[runGroups,runRows]);
 const matchingRows=useMemo(()=>applyDrilldown(filterCards(runRows,filters,peerEvidence),activeDrilldown,shopId,selectedRunId),[runRows,filters,peerEvidence,activeDrilldown,shopId,selectedRunId]);
 const candidateGroups=useMemo(()=>relatedCandidates(runGroups,runRows,matchingRows),[runGroups,runRows,matchingRows]);
 const candidateRows=useMemo(()=>[...new Map(candidateGroups.flatMap(x=>x.rows).map(r=>[r.observation_id,r])).values()],[candidateGroups]);
 useEffect(()=>{if(drilldown?.shop_id===shopId){setActiveDrilldown(drilldown);setFilters({...EMPTY_FILTERS});setFilter('run_id',drilldown.run_id);}},[drilldown,shopId]);
 useEffect(()=>{setPage(0);setDetail(null);setExportDocument(null);},[selectedRunId,filters,matchingRows]);
 const copyFilteredJson=async()=>{
  if(!exportDocument)return;
  const {token,text}=exportDocument;
  const updateExport=patch=>setExportDocument(current=>current?.token===token?{...current,...patch}:current);
  updateExport({copying:true,message:'正在复制完整 JSON…'});
  try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(text);updateExport({copying:false,message:'完整筛选 JSON 已复制。'});}
  catch{updateExport({copying:false,message:'复制失败：浏览器未允许访问剪贴板。下方仅为最多6000字符预览，不能当作完整JSON；请使用已交付的完整JSON文件。'});}
 };
 const downloadFilteredJson=()=>{
  if(!exportDocument)return;
  const {token,text}=exportDocument;
  try{requestJsonDownload(text);setExportDocument(current=>current?.token===token?{...current,message:'已请求浏览器下载；是否保存请查看浏览器下载记录。'}:current);}
  catch{setExportDocument(current=>current?.token===token?{...current,message:'下载请求未能发出。可尝试复制完整JSON，或使用已交付的完整JSON文件；下方预览不是全文。'}:current);}
 };
 if(!run||!queries.observations)return <section className="pdd-dashboard"><p>当前店铺尚无可读取的真实观察数据；尚未采集不等于没有商品。</p></section>;
 const scope=[...shopScope(shopId),{field:'run_id',label:`店铺范围：${run.shop_name||shopId} · 观察轮次`,value:run.run_id}],selectedScope=[...scope,...(activeDrilldown?[{field:'observation_id',label:'维度下钻范围',value:activeDrilldown.label}]:[]),...filterScope(filters)];
 const labelPairs=[...new Set(runRows.filter(r=>r.sales_label).map(labelUnitKey))],labelNames=Object.fromEntries(labelPairs.map(k=>[k,JSON.parse(k).map(x=>x||'单位未知').join(' · ')]));
 const update=(field,value)=>setFilters(f=>({...f,[field]:value,...(['band','labelUnit'].includes(field)?{salesMin:'',salesMax:'',watchBand:'custom'}:{})})),reset=()=>{setFilters({...EMPTY_FILTERS});setActiveDrilldown(null);},selectRun=value=>{setActiveDrilldown(null);setFilter('run_id',value);setFilters({...INITIAL_FILTERS});};
 const partial=run.status!=='complete'||!run.end_boundary_observed,latest=run.run_id===[...runs].sort((a,b)=>b.observed_to_epoch-a.observed_to_epoch)[0]?.run_id;
 const metrics=[{id:'pdd-kpi-eligible',title:'销量 >10 件',band:'eligible',note:'主清单达标',tone:'positive'},{id:'pdd-kpi-positive',title:'已有销量',band:'yipin',note:'精确正数卡片'},{id:'pdd-kpi-boundary',title:'销量 =10 件',band:'boundary',note:'临界，尚未达标',tone:'boundary'},{id:'pdd-kpi-unknown',title:'销量未知',band:'missing',note:'未显示，保留未知'}];
 const pages=Math.max(1,Math.ceil(matchingRows.length/24)),activePage=Math.min(page,pages-1),displayed=matchingRows.slice(activePage*24,activePage*24+24),matchedIds=new Set(matchingRows.map(r=>r.observation_id));
 const runLabels=Object.fromEntries(runs.map(r=>[r.run_id,`${r.status==='complete'&&r.end_boundary_observed?'完整参考':'部分采集'} · ${beijing(r.observed_to,true)} · ${r.card_count} 卡`]));
 const activeFilterCount=Object.keys(EMPTY_FILTERS).filter(k=>!['sort','watchBand'].includes(k)&&filters[k]!==EMPTY_FILTERS[k]).length;
 const issues=strategyIssues(filters),priceActive=filters.priceMin!==''||filters.priceMax!=='',unknownPriceRows=priceActive?applyDrilldown(filterCards(runRows,{...filters,priceMin:'',priceMax:''},peerEvidence),activeDrilldown,shopId,selectedRunId).filter(row=>parseDisplayPrice(row.price_raw).fen===null):[];
 const cachedRows=runRows.filter(row=>imageState(row)==='cached'),blockedRows=runRows.filter(row=>imageState(row)==='blocked');
 const controls=<div className="pdd-filter-controls"><label className="pdd-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg><input aria-label="搜索标题、列表位置或商品 ID" value={filters.search} onChange={e=>update('search',e.target.value)} placeholder="搜标题、位置 #382 或商品 ID"/></label>
 <Dropdown label="销量口径" allLabel="全部标签与单位" showLabel value={filters.labelUnit} choices={['all',...labelPairs]} choiceLabels={{all:'全部标签与单位',...labelNames}} onChange={v=>update('labelUnit',v)}/><Dropdown label="销量分档" allLabel={BAND_LABELS.all} showLabel value={filters.band} choices={Object.keys(BAND_LABELS)} choiceLabels={BAND_LABELS} onChange={v=>update('band',v)}/>
 <Dropdown label="主图" allLabel="全部图片状态" showLabel value={filters.image} choices={['all','cached','pending','blocked']} choiceLabels={{all:'全部图片状态',...IMAGE_LABELS}} onChange={v=>update('image',v)}/><Dropdown label="商品 ID" allLabel="全部身份状态" showLabel value={filters.identity} choices={['all','unique','unknown','conflict']} choiceLabels={{all:'全部身份状态',unique:'ID 本轮唯一',unknown:'ID 待补 / 无效',conflict:'身份冲突'}} onChange={v=>update('identity',v)}/>
 <Dropdown label="排序" allLabel="全部排序" showLabel value={filters.sort} choices={['sales','evidence','order']} choiceLabels={{evidence:'先看资料齐备卡片',order:'原列表顺序',sales:'销量从高到低'}} onChange={v=>update('sort',v)}/>{activeFilterCount>0&&<button className="pdd-reset" onClick={reset}>清除 {activeFilterCount} 项筛选</button>}</div>;
 return <article className="pdd-dashboard"><SectionHeader id="pdd-round-heading" title="本轮参考" filters={<Dropdown label="观察轮次" allLabel="全部轮次" showLabel value={run.run_id} choices={runs.map(r=>r.run_id)} choiceLabels={runLabels} onChange={selectRun}/>}/>
 <div className={`pdd-round-banner${partial?' pdd-round-partial':''}`} data-reviewed-rows="true"><div><span className="pdd-round-label">{partial?(latest?'最新部分采集':'历史部分采集'):'历史完整参考'}</span><strong>{runRows.length} 张原始卡片</strong></div><p>{beijing(run.observed_from)} — {beijing(run.observed_to)}（北京时间）</p><small>{partial?'本轮未到店铺结束边界，仅代表已采到的范围；不能据缺失判断下架。':'已观察店铺结束边界。完整参考保留独立观察时间，不与较新的部分采集合并。'}</small></div>
 {activeDrilldown&&<div className="portfolio-drilldown" data-reviewed-rows="true"><div><strong>当前下钻：{activeDrilldown.label}</strong><small>此范围保留全部原卡，低销量与未知值不会被默认门槛排除；可继续组合筛选。</small></div><button className="pdd-text-button" onClick={reset}>清除下钻范围，查看本轮全部卡片</button></div>}
 <SortableRegion id="pdd:metrics" variant="freeform" authoredRevision={1} className="pdd-metrics">{metrics.map(m=>{const rows=runRows.filter(r=>bandMatches(r,m.band));return <SortableItem key={m.id} id={m.id} label={m.title} kind="metric"><DataComponent onOpen={openSource} variant="card" id={m.id} queryId="observations" kind="metric" title={m.title} description={`本轮${m.note}的原始卡片数；点击数值只定位此范围，并清除其他商品筛选。`} sourceRows={rows} displayRows={rows} scopeFilters={[...scope,...filterScope({...EMPTY_FILTERS,band:m.band})]} className={`pdd-metric pdd-tone-${m.tone||'neutral'}`}><button className="pdd-metric-button" onClick={()=>{setActiveDrilldown(null);setFilters({...EMPTY_FILTERS,band:m.band});}} aria-label={`定位${m.title} ${rows.length} 张卡片`} data-reviewed-rows="true"><strong>{rows.length}</strong><span>{m.note} <b>↗</b></span></button></DataComponent></SortableItem>;})}</SortableRegion>
 <p className="pdd-key-rule" data-editable-id="pdd-critical-policy">一张卡片是一条观察，不能当作唯一 SKU；不同销量标签和单位独立保留。跨轮变化请到“更新与变化”核查身份、基线与逐条证据。</p>
 <DataComponent onOpen={openSource} id="pdd-image-coverage" queryId="observations" kind="metric" title="本轮主图覆盖" variant="plain" sourceRows={runRows} displayRows={runRows} scopeFilters={scope} className="pdd-coverage" description="以本轮原卡计数，已有本地图、待补和历史失败为互斥状态。"><span data-reviewed-rows="true">{cachedRows.length} / {runRows.length} 张已有本地图 · {runRows.length-cachedRows.length-blockedRows.length} 张待补 · {blockedRows.length} 张历史失败 / 限制</span></DataComponent>
 <StrategyControls filters={filters} setFilters={setFilters} onRestore={()=>setActiveDrilldown(null)}/>
 {visible('pdd-cards')&&<Section id="pdd-locator-heading" title="定位商品卡片" spacing="content" filters={controls}><DataComponent onOpen={openSource} id="pdd-cards" queryId="observations" queryIds={['observations','candidate_groups']} kind="table" title="筛选结果" variant="plain" sourceRows={matchingRows} displayRows={matchingRows} sourceRowsByQuery={{observations:matchingRows,candidate_groups:candidateGroups.map(item=>item.group)}} scopeFilters={selectedScope} description="来源、复制和 JSON 导出包含当前筛选的全部卡片，不只当前页。同标题理由来自本轮候选组，不确认同 SKU，不累计销量；展示价保留原文。" headerControls={<button className="pdd-export" onClick={()=>setExportDocument(prepareFilteredExport(matchingRows,run,filters,peerEvidence,activeDrilldown))}>导出筛选 JSON</button>}>
 <div className="pdd-results-meta" data-reviewed-rows="true"><strong>{matchingRows.length} <span>/ {runRows.length} 张卡片</span></strong><span>{filters.sort==='evidence'?'本地图优先 → ID 可查 → 原位置；仅方便核验。':filters.sort==='sales'?SALES_SORT_DESCRIPTION:'保持原列表顺序。'}</span></div>
 {issues.length>0&&<div className="pdd-rule-error" role="alert">{issues.join(' ')}</div>}{priceActive&&<p className="pdd-filter-note">仅纳入可解析的单一原展示金额；不代表采购成本或实际到手价。</p>}
 {matchingRows.length===0?<div className="pdd-empty">没有符合当前条件的卡片。{partial&&'本轮是部分采集，不能推断全店没有达标品。'}<button className="pdd-text-button" onClick={reset}>清除筛选</button></div>:<div className="pdd-products">{displayed.map(r=><Card key={r.observation_id} row={r} images={images} onSelect={setDetail} peerEvidence={peerEvidence}/>)}</div>}
 <div className="pdd-pagination"><span>{matchingRows.length?`${activePage*24+1}–${Math.min((activePage+1)*24,matchingRows.length)}`:'0'} / {matchingRows.length}</span><div><button disabled={activePage===0} onClick={()=>setPage(activePage-1)}>上一页</button><span>{activePage+1} / {pages}</span><button disabled={activePage+1>=pages} onClick={()=>setPage(activePage+1)}>下一页</button></div></div></DataComponent></Section>}
 {priceActive&&<DataComponent onOpen={openSource} id="pdd-price-excluded" queryId="observations" kind="metric" title="价格未知排除" variant="plain" sourceRows={unknownPriceRows} displayRows={unknownPriceRows} scopeFilters={[...scope,...(activeDrilldown?[{field:'observation_id',label:'维度下钻范围',value:activeDrilldown.label}]:[]),...filterScope({...filters,priceMin:'',priceMax:''}),{field:'price_raw',label:'单一原展示金额解析',value:'缺失、范围或多值不可确定'}]} className="pdd-price-excluded" description="满足其他筛选、因展示金额缺失或不能严格解析而排除的卡片；不将未知当作零。"><p data-reviewed-rows="true">满足其他条件的 {unknownPriceRows.length} 张卡片因展示金额未知被排除；原文仍保留，清除价格范围可恢复。</p></DataComponent>}
 {visible('pdd-candidates')&&<Section id="pdd-candidate-heading" title="相关同标题候选" spacing="section"><DataComponent onOpen={openSource} id="pdd-candidates" queryId="observations" queryIds={['observations','candidate_groups']} kind="table" title="逐卡对照" variant="plain" sourceRows={candidateRows} displayRows={candidateRows} sourceRowsByQuery={{observations:candidateRows,candidate_groups:candidateGroups.map(x=>x.group)}} scopeFilters={[...scope,{field:'observation_id',label:'候选范围',value:'与当前结果相关，保留本轮全组成员'}]} description="同标题候选不确认同设计或同 SKU；不累计销量。来源与复制包含本轮全组成员，包括低销量与缺失对照。"><p className="pdd-candidate-note" data-reviewed-rows="true">与当前结果相关的 {candidateGroups.length} 组；展开包含本轮全组成员，低销量与缺失卡片也保留。</p>
 {candidateGroups.length===0?<p className="pdd-empty">当前结果没有已建立的同标题候选组。</p>:<div className="pdd-candidates">{candidateGroups.map(({group,rows,matchedCount})=><details key={group.group_id} className="pdd-candidate" data-reviewed-rows="true"><summary><span className="pdd-group-code">{group.group_code}</span><span className="pdd-group-title">{group.normalized_title}</span><span className="pdd-group-count">{matchedCount} 条匹配 · 全组 {rows.length} 条</span></summary><div className="pdd-products pdd-compare-grid">{rows.map(r=><Card key={r.observation_id} row={r} images={images} onSelect={setDetail} comparison matched={matchedIds.has(r.observation_id)} peerEvidence={peerEvidence}/>)}</div></details>)}</div>}</DataComponent></Section>}
 <details className="pdd-evidence pdd-page-evidence"><summary>口径与轮次来源</summary><p>已有本地图、图片待补、失败 / 限制待复核为互斥状态。只显示本地已保存图片；不会自动请求原图或重试失败。精确销量 10 件不达主清单门槛，模糊与缺失不补零。</p><p>11–30 / 31–100 / &gt;100 是可调整的人工观察档。自定义范围可探索低销量，单卡 &gt;10 的主门槛标记始终独立保留；同标题不证同 SKU，销量不相加。资料排序仅方便人工核验，不是盈利、爆款或增长评分。</p><p>上新排序、首次观察、图片日期均不是已核实上架日期。原展示金额只严格解析单一 ¥ 数字（可含“券后”）；范围、多值及缺失不猜测。用户采购成本、起订量、运费和试款预算未知，无法判断可盈利。</p><dl><dt>轮次</dt><dd>{run.run_id}</dd><dt>完整 / 部分</dt><dd>{partial?'部分':'完整'}</dd><dt>结束边界</dt><dd>{run.end_boundary_observed?'已看到':'未看到'}</dd><dt>快照 SHA-256</dt><dd>{run.snapshot_sha256}</dd><dt>部分采集停止原因</dt><dd>{run.collection_stop_reason||'无已记录中断'}</dd></dl></details><Detail row={detail} run={run} images={images} filters={filters} peerEvidence={peerEvidence} matched={Boolean(detail&&matchedIds.has(detail.observation_id))} onClose={()=>setDetail(null)}/><FilteredExportDialog document={exportDocument} onClose={()=>setExportDocument(null)} onCopy={copyFilteredJson} onDownload={downloadFilteredJson}/>{activeSource&&<SourceSidebar key={activeSource.id} component={activeSource} queries={queries} getSource={queryId=>historyReviewedSource(queries,activeSource,queryId)} onClose={()=>setSourceRequest(null)}/>}</article>;
}
