import {verifiedCardImage} from './verified-image.js';
import React,{useMemo,useState} from 'react';
import {DataComponent,EvidenceChart,Dropdown,Section,SectionHeader,SourceSidebar,Tabs,useDataApp} from '../../data-app-public.jsx';
import {beijing} from './pdd-model.js';
import {trendRange,warehouseSource,lifecycleSummary,DELTA_LABELS,PRICE_LABELS} from './warehouse-model.js';
import {focusView,focusSortLabel,nextFocusSort,focusComparisonCounts,comparisonValue,comparisonDisplayValue,comparisonStatus,comparisonDate,displayClueSeries,formatGrowth,FOCUS_CATEGORIES,COMPARISON_LABELS,MATCH_LABELS} from './warehouse-focus-model.js';
import {displayHistoryRange,displayHistoryStatus} from './warehouse-display-history-model.js';
import './warehouse.css';
import {TrendDecisionPanel} from './TrendDecisionPanel.jsx';
import {ProductForecastPanel} from './ProductForecastPanel.jsx';
import {productDisplayName} from './product-display-name.js';
import {dataUpdateTime} from './data-time.js';
import {OccasionProducts} from './OccasionProducts.jsx';
import {occasionSummary} from './occasion-model.js';
import {SkuDialog} from './CollectionControls.jsx';
import {skuEligible} from './sku-model.js';
import {ZoomableImage} from './ZoomableImage.jsx';
import {PRODUCT_CATEGORIES,productCategories,productCategorySummary,dailyDiscoverySummary,trackingRows,trackingPage,discoveryLabel} from './warehouse-tracking-model.js';

export function WarehouseContent({shopId}){
 const {queries}=useDataApp();
 const [day,setDay]=useState(''),[search,setSearch]=useState(''),[trackId,setTrackId]=useState(''),[range,setRange]=useState('all'),[lane,setLane]=useState('all'),[page,setPage]=useState(0),[source,setSource]=useState(null),[priceCondition,setPriceCondition]=useState('coupon_after_display'),[comparison,setComparison]=useState('yesterday');
 const [productCategory,setProductCategory]=useState('all'),[showCategories,setShowCategories]=useState(false);
 const [occasion,setOccasion]=useState('all'),[occasionStates,setOccasionStates]=useState({});
 const [sort,setSort]=useState(null),[skuRow,setSkuRow]=useState(null);
 const focus=useMemo(()=>focusView(queries,shopId,day),[queries,shopId,day]),data=focus.warehouse,catalogue=focus.day,catalogueDate=focus.date;
 const occasionStateKey=`${shopId}:${catalogue?.run_id}:${occasion}`;
 const occasionCounts=useMemo(()=>({birthday:occasionSummary(focus.rows,'birthday').total,activity:occasionSummary(focus.rows,'activity').total}),[focus.rows]);
 const selectedDay=data.days.find(d=>d.date===day)||data.days[0],date=selectedDay?.date||'';
 const types=useMemo(()=>productCategorySummary(focus.rows),[focus.rows]),discoveries=useMemo(()=>dailyDiscoverySummary(focus.rows),[focus.rows]);
 const discoveryReady=focus.rows.length===0||focus.rows.every(row=>typeof row.discovery_status==='string');
 const cards=useMemo(()=>trackingRows(focus.rows,{lane,search,comparison,sort,productCategory}),[focus.rows,lane,search,comparison,sort,productCategory]),sortLabel=!sort&&['all','daily_new'].includes(lane)?'店内上新顺序':focusSortLabel(sort,lane);
 const selected=trackId?focus.rows.find(r=>r.track_id===trackId):null,clue=displayClueSeries(selected),baselineDate=comparisonDate(catalogueDate,comparison);
 const displayHistory=useMemo(()=>displayHistoryRange(queries.warehouse_display_history?.rows||[],selected,date,range),[queries.warehouse_display_history,selected,date,range]);
 const dailyIncreaseRows=displayHistory.plot.filter(row=>!row.comparison_break);
 const displayHistoryObservations=(queries.observations?.rows||[]).filter(row=>displayHistory.observationIds.includes(row.observation_id));
 const clueObservations=(queries.observations?.rows||[]).filter(r=>clue.observationIds.includes(r.observation_id)),clueEvidence=focus.source.filter(r=>r.observation_id===selected?.observation_id);
 const trend=useMemo(()=>trendRange(data.points,selected?.track_id,date,range),[data.points,selected?.track_id,date,range]);
 const priorityRows=focus.rows.filter(r=>r.category==='yipin_gt10');
 const current=trend.source.at(-1),lifecycle=lifecycleSummary(trend.source),comparisonCounts=focusComparisonCounts(priorityRows,comparison);
 const assets=new Map((queries.image_assets?.rows||[]).map(r=>[r.sha256,r]));
 const scope=[{field:'shop_id',label:'店铺',value:shopId}],cardScope=[...scope,{field:'date',label:'清单日期',value:catalogueDate},{field:'category',label:'商品分类',value:lane==='all'?'全部商品':lane==='daily_new'?'当日首次监测记录':lane==='rapid'?'快速增长':lane==='rising'?'展示销量上涨':FOCUS_CATEGORIES[lane]},{field:'product_category',label:'标题品类',value:PRODUCT_CATEGORIES[productCategory]||'全部品类'},{field:'comparison',label:'对比日期',value:`${COMPARISON_LABELS[comparison]} ${baselineDate}`},{field:'search',label:'搜索',value:search||'全部'},{field:'sort',label:'排序',value:`${sortLabel}${sort?'；无可比数据置后':''}`}],trendScope=[...scope,{field:'track_id',label:'商品或独立原卡',value:selected?.track_id||'无'},{field:'date',label:'日期范围（北京时间）',value:`${trend.startDate} 至 ${date}`}];
 const openSource=(action,component)=>{if(action==='source')setSource(component);else if(action==='close')setSource(null);};
 const evidence=(id,queryId,rows,filters=scope)=>({id,queryId,sourceRows:rows,displayRows:rows,scopeFilters:filters,onOpen:openSource});
 const originalRecords=(rows,all=data.watchRecords)=>{const ids=new Set(rows.map(r=>r.observation_id));return all.filter(r=>ids.has(r.observation_id));};
 const observations=(queries.observations?.rows||[]).filter(r=>trend.source.some(p=>p.observation_id===r.observation_id||p.baseline_observation_id===r.observation_id));
 const cardSources=originalRecords(cards,focus.source),cardIds=new Set(cards.flatMap(r=>[r.observation_id,r.yesterday_baseline_observation_id,r.day_before_yesterday_baseline_observation_id])),cardObservations=(queries.observations?.rows||[]).filter(r=>cardIds.has(r.observation_id));
 const {maxPage,currentPage,shown}=trackingPage(cards,page);
 const salesCount=trend.source.filter(p=>Number.isFinite(p.cumulative_yipin)).length;
 const priceSource=trend.source.filter(p=>p.price_condition===priceCondition),priceRows=trend.plot.map(p=>({...p,display_price_yuan:p.price_condition===priceCondition?p.display_price_yuan:null})),priceCount=priceSource.filter(p=>Number.isFinite(p.display_price_yuan)).length;
 const chartEvidence={displayRows:trend.plot,queryId:'warehouse_points',queryIds:['warehouse_points','observations'],sourceRows:trend.source,sourceRowsByQuery:{warehouse_points:trend.source,observations},scopeFilters:trendScope,onOpen:openSource,height:260,variant:'plain'};
 const reset=()=>{setPage(0);setTrackId('');setSource(null);setSkuRow(null);};
 const changeLane=value=>{setLane(value);reset();};
 const changeDay=value=>{setDay(value);setSearch('');setLane('all');setProductCategory('all');setSort(null);reset();};
 const changeProductCategory=value=>{setProductCategory(value);reset();};
 const changeSort=field=>{setSort(current=>nextFocusSort(current,field));reset();};
 const openProduct=row=>{setTrackId(row.track_id);setSource(null);if(typeof window!=='undefined')window.scrollTo({top:0,behavior:'auto'});};
 const skuDialog=<SkuDialog row={skuRow?.shop_id===shopId?skuRow:null} shopId={shopId} onClose={()=>setSkuRow(null)}/>;
 const comparisonControls=<Dropdown label="销量对比" showLabel value={comparison} choices={Object.keys(COMPARISON_LABELS)} choiceLabels={Object.fromEntries(Object.entries(COMPARISON_LABELS).map(([key,label])=>[key,`${label} · ${comparisonDate(catalogueDate,key)}`]))} onChange={value=>{setComparison(value);reset();}}/>;
 if(!selectedDay)return <article className="pdd-warehouse"><h2>上新监测数据舱</h2><p>本店尚无采集记录。</p></article>;
 const warehouseHeading=<>
  <SectionHeader id="warehouse-heading" title="商品追踪清单" filters={<Dropdown label="监测截至日期" showLabel value={date} choices={data.days.map(d=>d.date)} onChange={changeDay}/>}/>
  <Tabs id="warehouse-occasion-tabs" label="商品查询模块" variant="pills" value={occasion} onChange={value=>{setOccasion(value);reset();}} items={[{id:'all',label:`全部商品 · ${focus.rows.length}`},{id:'birthday',label:`生日 / 纪念日 · ${occasionCounts.birthday}`},{id:'activity',label:`活动 / 应援 · ${occasionCounts.activity}`}]} />
  <DataComponent {...evidence('warehouse-data-updated','warehouse_days',catalogue?[catalogue]:[])} kind="metric" title="数据更新时间" variant="plain"><div className="warehouse-update-line" data-reviewed-rows="true"><strong>数据更新：<time dateTime={catalogue?.observed_to}>{dataUpdateTime(catalogue?.observed_to)}</time><span>（北京时间）</span></strong><small>当天重复采集更新当天数据，历史日期保留</small></div></DataComponent>
 </>;
 if(selected)return <article className="pdd-warehouse warehouse-product-detail">
  <div className="warehouse-detail-heading"><button type="button" className="warehouse-back-button" onClick={()=>{setTrackId('');setSource(null);if(typeof window!=='undefined')window.scrollTo({top:0,behavior:'auto'});}}>← 返回商品清单</button><div><h2 title={selected.title}>{productDisplayName(selected.title)}</h2><small data-reviewed-rows="true">{FOCUS_CATEGORIES[selected.category]||'商品观察'} · 记录 #{selected.observation_id} · {catalogueDate}</small><small className="warehouse-product-updated" data-reviewed-rows="true">数据更新：<time dateTime={selected.observed_at}>{dataUpdateTime(selected.observed_at)}</time>（北京时间）</small></div>{skuEligible(selected)&&<button type="button" className="warehouse-sku-button" onClick={()=>setSkuRow(selected)}>查看 SKU</button>}</div>
  {selected&&displayHistory.source.length>0&&<Section id="warehouse-display-history-section" title="商品每日变化" spacing="content" filters={<Dropdown label="时间范围" allLabel="全部日期" showLabel value={range} choices={['all','30','90','365']} choiceLabels={{all:'全部日期',30:'最近30天',90:'最近90天',365:'最近365天'}} onChange={value=>{setRange(value);setSource(null);}}/>}>
   <EvidenceChart {...evidence('warehouse-display-daily-increase','warehouse_display_history',displayHistory.source,[...scope,{field:'anchor_observation_id',label:'当前商品原卡',value:selected.observation_id},{field:'date',label:'显示日期',value:`${displayHistory.startDate} 至 ${date}`}])} queryIds={['warehouse_display_history','observations']} sourceRowsByQuery={{warehouse_display_history:displayHistory.source,observations:displayHistoryObservations}} displayRows={dailyIncreaseRows} title="每日增加（件）" description="按日期展示前台销量数较前一天的增加量；缺基线、缺采和无法比较的日期留空。同标题同图的匹配仍为展示线索。" spec={{type:'bar',x:'date',y:'daily_delta',stackable:false,showValues:true,valueDecimals:0,yLabel:'较前日增加（件）',legend:{labels:{daily_delta:'每日增加（件）'}}}} rows={dailyIncreaseRows} height={280} variant="plain">
    <small className="warehouse-daily-increase-note">柱顶数字为该日较前一天的增加量；无前日记录不画柱。</small>
   </EvidenceChart>
   <details className="warehouse-details"><summary>累计销量折线</summary>
   <EvidenceChart {...evidence('warehouse-display-history-chart','warehouse_display_history',displayHistory.source,[...scope,{field:'anchor_observation_id',label:'当前商品原卡',value:selected.observation_id},{field:'date',label:'显示日期',value:`${displayHistory.startDate} 至 ${date}`}])} queryIds={['warehouse_display_history','observations']} sourceRowsByQuery={{warehouse_display_history:displayHistory.source,observations:displayHistoryObservations}} displayRows={displayHistory.plot} title={selected.title||'商品每日变化'} description={displayHistory.hasClues?'含同标题同图展示线索；缺采和未匹配日期留空。':'按已记录日期展示，缺采日期留空。'} spec={{type:'line',x:'date',y:'cumulative_yipin',stackable:false,valueDecimals:0,yLabel:'销量展示（件）'}} rows={displayHistory.plot} height={260} variant="plain"/>
   </details>
   <DataComponent {...evidence('warehouse-display-history-days','warehouse_display_history',displayHistory.source,[...scope,{field:'anchor_observation_id',label:'当前商品原卡',value:selected.observation_id},{field:'date',label:'显示日期',value:`${displayHistory.startDate} 至 ${date}`}])} queryIds={['warehouse_display_history','observations']} sourceRowsByQuery={{warehouse_display_history:displayHistory.source,observations:displayHistoryObservations}} kind="table" title={`${displayHistory.source.length} 个已记录日期`} variant="plain"><div className="pdd-history-table-wrap"><table className="pdd-history-table" data-reviewed-rows="true"><thead><tr><th>日期</th><th className="warehouse-number">销量</th><th className="warehouse-number">日增量</th><th>展示价</th><th>对照</th></tr></thead><tbody>{displayHistory.source.map(p=><tr key={`${p.date}:${p.anchor_observation_id}`}><td>{p.date}</td><td className="warehouse-number">{p.cumulative_yipin??'—'}</td><td className="warehouse-number">{p.daily_delta==null?'—':`${p.daily_delta>0?'+':''}${p.daily_delta}`}</td><td>{p.price_raw||(p.display_price_yuan==null?'—':`¥${p.display_price_yuan}`)}</td><td title={p.observation_id==null?'未找到可确认的对应原卡':`原卡 #${p.observation_id}`}>{displayHistoryStatus(p)}</td></tr>)}</tbody></table></div></DataComponent>
  </Section>}
  {selected&&!displayHistory.source.length&&clue.source.length>=2&&<Section id="warehouse-clue-section" title="同标题同图展示变化 · 待核实" spacing="content">
   <EvidenceChart {...evidence('warehouse-clue-chart',focus.queryId,clueEvidence,[...scope,{field:'observation_id',label:'当前原卡',value:selected.observation_id},{field:'comparison_basis',label:'对照依据',value:'同标题同原图，两日各自唯一；原卡独立，不合并商品轨迹'}])} queryIds={[focus.queryId,'observations']} sourceRowsByQuery={{[focus.queryId]:clueEvidence,observations:clueObservations}} displayRows={clue.plot} title={selected.title||'商品展示变化'} spec={{type:'line',x:'date',y:'display_yipin',stackable:false,valueDecimals:0,yLabel:'前台销量展示（件）'}} rows={clue.plot} height={220} variant="plain"/>
   <DataComponent {...evidence('warehouse-clue-days',focus.queryId,clueEvidence)} queryIds={[focus.queryId,'observations']} sourceRowsByQuery={{[focus.queryId]:clueEvidence,observations:clueObservations}} displayRows={clue.source} kind="table" title="逐日原卡对照" variant="plain"><div className="pdd-history-table-wrap"><table className="pdd-history-table" data-reviewed-rows="true"><thead><tr><th>日期</th><th className="warehouse-number">前台销量</th><th>原卡</th><th>依据</th></tr></thead><tbody>{clue.source.map(p=><tr key={p.observation_id}><td>{p.date}</td><td className="warehouse-number">{p.display_yipin}</td><td>#{p.observation_id}</td><td>{p.basis==='current_card'?'当前原卡':'同标题同图，身份待核实'}</td></tr>)}</tbody></table></div><small>此处是展示变化线索；下方已确认商品轨迹独立保留。</small></DataComponent>
  </Section>}
  {selected&&<details className="warehouse-details" open={!displayHistory.source.length&&clue.source.length<2}><summary>{clue.source.length>=2?'独立原卡记录与已确认轨迹':'商品时间线与每日记录'}</summary><Section id="warehouse-trend-section" title="商品生命周期 · 每日变化" spacing="content" filters={<Dropdown label="时间范围" allLabel="全部日期" showLabel value={range} choices={['all','30','90','365']} choiceLabels={{all:'全部监测时间',30:'最近30天',90:'最近90天',365:'最近365天'}} onChange={value=>{setRange(value);setSource(null);}}/>}>
   <DataComponent {...evidence('warehouse-product-info','warehouse_points',trend.source,trendScope)} queryIds={['warehouse_points','warehouse_watch_records']} sourceRowsByQuery={{warehouse_points:trend.source,warehouse_watch_records:originalRecords([selected])}} kind="metric" title={selected.title||'所选原卡'} variant="plain">
    <p data-reviewed-rows="true">{selected.identity_basis==='verified_goods_id'?`按本店可靠商品 ID ${selected.goods_id} 追踪。`:'本卡先保留独立历史；上方同标题同图对比另列为变化线索。'}{selected.monitor_first_date?` 首次监测 ${selected.monitor_first_date}，实际上架日期未核实。`:' 首次监测仅有观察窗口，实际上架日期未核实。'} 最近实际记录：{current?.date||'未知'}。</p>
    <div className="warehouse-stats" data-reviewed-rows="true"><div><strong>{current?.cumulative_yipin??'未知'}</strong><span>最近记录累计销量（件）</span></div><div><strong>{current?.daily_delta??'未知'}</strong><span>最近记录日增量 · {DELTA_LABELS[current?.delta_status]||'无记录'}</span></div><div><strong>{lifecycle.comparable_days}</strong><span>范围内可比日增量记录</span></div><div><strong>{lifecycle.peak_delta??'未知'}</strong><span>已记录峰值日增量{lifecycle.peak_day?` · ${lifecycle.peak_day}`:''}</span></div></div>
    <p data-reviewed-rows="true">{lifecycle.status}。曲线用于查看起量、持续和回落；数据不足时不判断生命周期阶段。销量为前台展示数，未核实订单。</p>
   </DataComponent>
   <div className="warehouse-charts">
    {salesCount>=2?<EvidenceChart {...chartEvidence} id="warehouse-sales-chart" title="累计销量（件）" spec={{type:'line',x:'date',y:'cumulative_yipin',stackable:false,yLabel:'累计销量（件）',valueDecimals:0}} rows={trend.plot}/>:<DataComponent {...evidence('warehouse-sales-chart','warehouse_points',trend.source,trendScope)} kind="metric" title="累计销量（件）" variant="plain"><div className="warehouse-await" data-reviewed-rows="true"><strong>{current?.cumulative_yipin??'未知'}</strong><p>{salesCount===1?'仅一个有效日期，等待后续监测形成曲线。':'此范围没有精确销量件数。'}</p></div></DataComponent>}
    {lifecycle.comparable_days>=2?<EvidenceChart {...chartEvidence} id="warehouse-delta-chart" title="每日销量增量（件）" spec={{type:'bar',x:'date',y:'daily_delta',stackable:false,valueDecimals:0}} rows={trend.plot}/>:<DataComponent {...evidence('warehouse-delta-chart','warehouse_points',trend.source,trendScope)} kind="metric" title="每日销量增量（件）" variant="plain"><div className="warehouse-await" data-reviewed-rows="true"><strong>{current?.daily_delta??'未知'}</strong><p>需要连续日期、可靠同商品ID；已拼与已抢按同口径比较。缺采、模糊销量和负差值不补零。</p></div></DataComponent>}
    <div><Dropdown label="价格口径" showLabel value={priceCondition} choices={Object.keys(PRICE_LABELS)} choiceLabels={PRICE_LABELS} onChange={value=>{setPriceCondition(value);setSource(null);}}/>{priceCount>=2?<EvidenceChart {...chartEvidence} displayRows={priceRows} sourceRows={priceSource} sourceRowsByQuery={{warehouse_points:priceSource,observations:observations.filter(r=>priceSource.some(p=>p.observation_id===r.observation_id))}} scopeFilters={[...trendScope,{field:'price_condition',label:'价格口径',value:priceCondition}]} id="warehouse-price-chart" title={`${PRICE_LABELS[priceCondition]}（元）`} spec={{type:'line',x:'date',y:'display_price_yuan',stackable:false,currency:'CNY',valueDecimals:2}} rows={priceRows}/>:<DataComponent {...evidence('warehouse-price-chart','warehouse_points',priceSource,[...trendScope,{field:'price_condition',label:'价格口径',value:priceCondition}])} kind="metric" title={`${PRICE_LABELS[priceCondition]}（元）`} variant="plain"><div className="warehouse-await" data-reviewed-rows="true"><strong>{current?.price_condition===priceCondition&&current.display_price_yuan!=null?`¥${current.display_price_yuan.toFixed(2)}`:'未知'}</strong><p>不足两个同口径价格日期，等待后续监测。</p></div></DataComponent>}</div>
   </div>
   <DataComponent {...evidence('warehouse-product-days','warehouse_points',trend.source,trendScope)} queryIds={['warehouse_points','observations']} sourceRowsByQuery={{warehouse_points:trend.source,observations}} kind="table" title="逐日原文与来源" variant="plain"><div className="pdd-history-table-wrap"><table className="pdd-history-table" data-reviewed-rows="true"><thead><tr><th>日期 / 范围</th><th>销量原文 / 日增量</th><th>展示价原文</th><th>来源</th></tr></thead><tbody>{trend.source.map(p=><tr key={p.observation_id}><td>{p.date}<small>{p.is_complete?'完整轮':'部分轮'}</small></td><td>{p.sales_raw||'未显示'}<small>{p.daily_delta==null?'日增量未知':`日增量 +${p.daily_delta}`} · {DELTA_LABELS[p.delta_status]}</small></td><td>{p.price_raw||'未知'}</td><td><details><summary>原卡 #{p.observation_id}</summary><p>{p.run_id}</p><p>读取时间：{beijing(p.observed_at)}</p><p>快照 SHA：{p.snapshot_sha256}</p></details></td></tr>)}</tbody></table></div><p>缺采日期不填0、不沿用前日数据。</p></DataComponent>
  </Section></details>}
  {skuDialog}
  {source&&<SourceSidebar key={source.id} component={source} queries={queries} getSource={id=>warehouseSource(queries,source,id)} onClose={()=>setSource(null)}/>}
 </article>;
 if(occasion!=='all')return <article className="pdd-warehouse">
  {warehouseHeading}
  {catalogueDate!==date&&<div className="warehouse-attention" data-reviewed-rows="true">{date} 仅部分记录，当前展示 {catalogueDate} 完整采集。</div>}
  <OccasionProducts key={`${shopId}:${catalogue?.run_id}:${occasion}`} module={occasion} viewState={occasionStates[occasionStateKey]||{}} onViewStateChange={value=>setOccasionStates(current=>({...current,[occasionStateKey]:value}))} rows={focus.rows} sourceRows={focus.source} queryId={focus.queryId} observations={queries.observations?.rows||[]} assets={assets} shopId={shopId} date={catalogueDate} comparison={comparison} onComparisonChange={value=>{setComparison(value);setSource(null);}} onOpenProduct={openProduct} onOpenSku={setSkuRow} onOpenSource={openSource}/>
  {skuDialog}
  {source&&<SourceSidebar key={source.id} component={source} queries={queries} getSource={id=>warehouseSource(queries,source,id)} onClose={()=>setSource(null)}/>}
 </article>;
 return <article className="pdd-warehouse">
  {warehouseHeading}
  <DataComponent {...evidence('warehouse-growth-overview',focus.queryId,focus.source,[...scope,{field:'date',label:'清单日期',value:catalogueDate},{field:'category',label:'范围',value:'本店全部已采商品；新增为当日首次监测记录，品类取原始标题线索'}])} kind="metric" title={`${catalogueDate} · 全店商品追踪`} variant="plain">
   <div className="warehouse-priority-counts" data-reviewed-rows="true"><button type="button" onClick={()=>changeLane('yipin_gt10')} className={lane==='yipin_gt10'?'warehouse-count-active':''} aria-pressed={lane==='yipin_gt10'}><strong>{focus.counts.yipin_gt10}</strong><span>销量 &gt;10 · 可挑选</span></button><button type="button" onClick={()=>changeLane('yipin_1to10')} className={lane==='yipin_1to10'?'warehouse-count-active':''} aria-pressed={lane==='yipin_1to10'}><strong>{focus.counts.yipin_1to10}</strong><span>销量 1–10 · 重点观察</span></button><button type="button" onClick={()=>changeLane('rising')} className={lane==='rising'?'warehouse-count-active':''} aria-pressed={lane==='rising'}><strong>{comparisonCounts.comparable?comparisonCounts.increased:'—'}</strong><span>展示销量上涨 · &gt;10</span><small>按所选日期比较</small></button><button type="button" onClick={()=>changeLane('rapid')} className={lane==='rapid'?'warehouse-count-active':''} aria-pressed={lane==='rapid'}><strong>{comparisonCounts.comparable?comparisonCounts.confirmed+comparisonCounts.provisional:'—'}</strong><span>快速增长线索 · &gt;10</span><small>增长提示，等待持续观察</small></button></div>
  </DataComponent>
  <ProductForecastPanel key={`forecast:${shopId}:${catalogueDate}`} shopId={shopId} asOfDate={catalogueDate} onOpenProduct={openProduct}/>
  {catalogueDate!==date&&<div className="warehouse-attention" data-reviewed-rows="true">{date} 仅部分记录，当前展示 {catalogueDate} 完整采集。</div>}
  <div className="warehouse-tracking-actions"><button type="button" onClick={()=>{setLane('all');setSearch('');setSort(null);setProductCategory('all');setShowCategories(value=>!value);reset();}} aria-pressed={showCategories}>品类追踪</button></div>
  {showCategories&&<DataComponent {...evidence('warehouse-product-types',focus.queryId,focus.source,[...scope,{field:'date',label:'清单日期',value:catalogueDate}])} kind="metric" title="按品类查看商品" variant="plain"><div className="warehouse-category-counts" data-reviewed-rows="true"><button type="button" aria-pressed={productCategory==='all'} className={productCategory==='all'?'warehouse-category-active':''} onClick={()=>changeProductCategory('all')}><strong>{types.total}</strong><span>全部品类</span></button>{Object.entries(PRODUCT_CATEGORIES).filter(([key])=>types.counts[key]>0).map(([key,label])=><button key={key} type="button" aria-pressed={productCategory===key} className={productCategory===key?'warehouse-category-active':''} onClick={()=>changeProductCategory(key)}><strong>{types.counts[key]}</strong><span>{label}</span></button>)}</div><p className="warehouse-tracking-note">按原始标题识别，一张原卡可包含多个品类；具体规格以 SKU 为准。</p></DataComponent>}
  <Tabs id="warehouse-focus-tabs" label="商品数据表" value={lane} variant="pills" onChange={changeLane} items={[{id:'all',label:`全部商品 · ${focus.rows.length}`},{id:'daily_new',label:`当日新增 · ${discoveryReady?discoveries.count:'待生成'}`},{id:'yipin_gt10',label:`销量 >10 · ${focus.counts.yipin_gt10}`},{id:'yipin_1to10',label:`1–10件观察 · ${focus.counts.yipin_1to10}`},{id:'yipin_zero',label:`销量 0 · ${focus.counts.yipin_zero}`},{id:'unknown',label:`销量未显示 · ${focus.counts.unknown}`},{id:'other_label',label:`其他销量口径 · ${focus.counts.other_label}`},{id:'rising',label:`销量上涨 · ${comparisonCounts.increased}`},{id:'rapid',label:`快速增长 · ${comparisonCounts.confirmed+comparisonCounts.provisional}`}]} />
  <Section id="warehouse-cards-section" title={lane==='rapid'?`${COMPARISON_LABELS[comparison]}快速增长`:lane==='rising'?`${COMPARISON_LABELS[comparison]}展示销量上涨`:lane==='all'?'全部商品':lane==='daily_new'?`${catalogueDate} 首次监测记录`:`${FOCUS_CATEGORIES[lane]} · 商品表`} spacing="content" filters={<div className="warehouse-tracking-filters"><Dropdown label="商品品类" showLabel value={productCategory} choices={['all',...Object.keys(PRODUCT_CATEGORIES).filter(key=>types.counts[key]>0)]} choiceLabels={{all:`全部品类 · ${focus.rows.length}`,...Object.fromEntries(Object.entries(PRODUCT_CATEGORIES).map(([key,label])=>[key,`${label} · ${types.counts[key]}`]))}} onChange={changeProductCategory}/>{comparisonControls}<label className="pdd-search"><input type="search" aria-label="搜索数仓商品" value={search} placeholder="搜索商品标题 / 原卡" onChange={e=>{setSearch(e.target.value);reset();}}/></label></div>}>
   <p className="warehouse-tracking-note" data-reviewed-rows="true">本店已采 {focus.rows.length} 张原卡 · 当前筛选 {cards.length} 张 · 每页 25 张{lane==='daily_new'&&' · 新增为当日首次监测记录，不代表当日上架'}</p>
   {lane==='daily_new'&&discoveries.unresolved>0&&<p className="warehouse-tracking-note">另有 {discoveries.unresolved} 张新旧待核实原卡，保留在“全部商品”中查看。</p>}
   <DataComponent {...evidence('warehouse-cards',focus.queryId,cardSources,cardScope)} queryIds={[focus.queryId,'observations']} sourceRowsByQuery={{[focus.queryId]:cardSources,observations:cardObservations}} displayRows={cards} kind="table" title={`${cards.length} 张商品原卡`} variant="plain">
    <div className="pdd-history-table-wrap"><table className="pdd-history-table warehouse-focus-table" data-reviewed-rows="true"><thead><tr><th>图片 / 商品</th><th>展示价</th><th className="warehouse-number">当前销量<small>{catalogueDate}</small></th><th className="warehouse-number">{comparison==='yesterday'?'昨日':'前天'}销量<small>{baselineDate}</small></th>{[['delta','增加'],['growth_rate','涨幅']].map(([field,label])=><th key={field} className="warehouse-number" aria-sort={sort?.field===field?(sort.direction==='asc'?'ascending':'descending'):'none'}><button type="button" className="warehouse-sort-button" onClick={()=>changeSort(field)} aria-label={`${label}：点击按${sort?.field===field&&sort.direction==='desc'?'升序':'降序'}排序`} title={`按${label}${sort?.field===field&&sort.direction==='desc'?'升序':'降序'}排列，暂无可比数据排在最后`}>{label}<span aria-hidden="true">{sort?.field===field?(sort.direction==='asc'?'↑':'↓'):'↕'}</span></button></th>)}<th className="warehouse-action-cell">数据</th></tr></thead><tbody>{shown.map(r=>{const c=comparisonDisplayValue(r,comparison),image=verifiedCardImage(r,assets);return <tr key={r.observation_id} className={selected?.observation_id===r.observation_id?'warehouse-selected':''}>
     <td><div className="warehouse-product">{image?<span className="warehouse-image-source" title={r.image_content_kind==='store_search_variant'?'店内搜索同文件图片':'已保存商品主图'}><ZoomableImage src={image} alt={r.title||'商品图片'} className="warehouse-thumbnail"/></span>:<span className="warehouse-missing-image">待补图</span>}<div><span className="warehouse-title" title={r.title||'标题未记录'}>{productDisplayName(r.title)}</span><small>原卡 #{r.observation_id} · <span title={MATCH_LABELS[c.basis]||comparisonStatus(c.status)}>{c.basis==='confirmed_goods_id'?'已确认':c.basis==='provisional_title_image'?'同图线索':comparisonStatus(c.status)}</span></small><small className="warehouse-product-type">{productCategories(r.title).map(key=>PRODUCT_CATEGORIES[key]).join(" · ")}</small><small className="warehouse-product-first">{discoveryLabel(r)}{r.first_observed_date&&` · 首次监测 ${r.first_observed_date}`}</small><small className="warehouse-product-updated">更新于 <time dateTime={r.observed_at}>{dataUpdateTime(r.observed_at)}</time></small><details><summary>原始名称与对比依据</summary><p>{r.title}</p><p>{r.sales_raw||'销量未显示'} · {r.price_raw||'价格未显示'}</p><p>对照 {c.date||'无'} · {comparisonStatus(c.status)}</p>{c.basis==='provisional_title_image'&&<p>两日同店唯一同标题同原图的展示线索，原卡分别保留。</p>}</details></div></div></td>
     <td className="warehouse-price"><span className="warehouse-price-raw" title={r.price_raw||'价格未显示'}>{r.price_raw||'—'}</span></td><td className="warehouse-number"><strong>{r.yipin_value??'—'}</strong>{r.yipin_value==null&&<small>{r.sales_raw||'未显示'}</small>}</td><td className="warehouse-number">{c.value??'—'}</td><td className={`warehouse-number ${c.delta>0?'warehouse-increase':''}`}>{c.delta==null?'—':`${c.delta>0?'+':''}${c.delta}`}</td><td className="warehouse-number">{formatGrowth(c.rate,c.status)}</td><td className="warehouse-action-cell"><div className="warehouse-data-actions"><button type="button" className="warehouse-chart-button" onClick={()=>openProduct(r)} aria-label={`查看数据图表：${r.title||'商品'}`}>查看走势</button>{skuEligible(r)&&<button type="button" className="warehouse-sku-button" onClick={()=>setSkuRow(r)} aria-label={`查看 SKU：${r.title||'商品'}`}>查看 SKU</button>}</div></td>
    </tr>;})}</tbody></table></div>
    {!cards.length&&<p className="warehouse-empty">{search?'没有匹配商品。':lane==='rapid'?comparisonCounts.comparable?'这次对比没有达到快速增长条件的商品。':'对应日期尚无可对照记录，保留空表。':'该分类暂无商品。'}</p>}
    <div className="pdd-pagination"><span>{cards.length} 张原卡 · 按{sortLabel}{sort&&' · 无可比数据置后'}</span><div><button disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>上一页</button><span>{currentPage+1} / {maxPage}</span><button disabled={currentPage+1>=maxPage} onClick={()=>setPage(currentPage+1)}>下一页</button></div></div>
   </DataComponent>
  </Section>
  <TrendDecisionPanel shopId={shopId} asOfDate={catalogueDate} onOpenProduct={openProduct}/>
  <details className="warehouse-details"><summary>采集信息</summary><DataComponent {...evidence('warehouse-current','warehouse_days',[selectedDay,...(catalogue&&catalogue.run_id!==selectedDay.run_id?[catalogue]:[])])} kind="metric" title="采集记录" variant="plain"><div className="warehouse-collection-line" data-reviewed-rows="true"><span>{catalogueDate} · {catalogue?.is_complete?'全店完整采集':'部分采集'} · {catalogue?.card_count??'未知'} 张原卡</span><span>有图 {focus.rows.filter(r=>verifiedCardImage(r,assets)).length} / {focus.rows.length}</span><span>更新至 {beijing(catalogue?.observed_to)}</span>{catalogueDate!==date&&<span>{date} 仅部分记录 {selectedDay.card_count} 张</span>}</div></DataComponent></details>
  <details className="warehouse-details"><summary>查看统计口径</summary><p>默认展示店铺“上新”栏目全部已采商品，销量0、未显示及其他口径均保留并可查看走势。新增记录按本店历史首次监测日期识别，首轮建档存量不算新增；标题和原图变化、覆盖不足仍为候选或待核实，首次监测不是上架时间。标题品类可交叉，不将多类数量相加作全店总数。销量包含“已拼”和“已抢”，原始标签保留；当天采用最新完整版本，每日历史和原始轮次保留。</p><p>快速增长以当前清单日期对应的昨日或前天为基期，增量至少10且增幅至少30%；零基期增加至少10单独标记“从零起量”。同商品ID的确认结果和同标题同图的展示线索分开统计；无数据不填零，零基期不计算百分比。</p></details>
  <details className="warehouse-details"><summary>每日采集档案 · {data.days.length} 个日期</summary><Section id="warehouse-archive-section" title="每日记录与当天版本" spacing="content"><DataComponent {...evidence('warehouse-archive','warehouse_days',data.days)} kind="table" title="本店每日档案" variant="plain"><div className="pdd-history-table-wrap"><table className="pdd-history-table" data-reviewed-rows="true"><thead><tr><th>日期</th><th>有效版本</th><th>卡数 / 原始轮次</th><th>采集结束 / 来源</th></tr></thead><tbody>{data.days.map(d=><tr key={d.date}><td><button className="pdd-text-button" onClick={()=>changeDay(d.date)}>{d.date}</button></td><td>{d.is_complete?'当天最新完整轮':'当天仅部分轮'}{d.run_id!==d.latest_observed_run_id&&<small>后续部分轮保留，不替换完整结果</small>}</td><td>{d.card_count} 原卡<small>保留 {d.version_count} 个原始轮次</small></td><td>{beijing(d.observed_to)}<details><summary>全部原始轮次与有效SHA</summary><p>{d.all_run_ids.join('；')}</p><p>{d.snapshot_sha256}</p></details></td></tr>)}</tbody></table></div></DataComponent></Section></details>
  {skuDialog}
  {source&&<SourceSidebar key={source.id} component={source} queries={queries} getSource={id=>warehouseSource(queries,source,id)} onClose={()=>setSource(null)}/>}
 </article>;
}
